# storyboard: 8f2128c47ea33d0b
from aisr_kit import *

class S05(NarratedScene):
    def construct(self):
        with self.beat("s05b01") as b:
            heading = Heading("Back to the inbox")
            tag = Tag("future_scenario")
            source = Source("Meinke et al. (2024)")
            inbox_label = T("Hypothetical inbox", size=26).move_to([-4.5, 2.1, 0])
            tray = Node("Input path", color=TEAL, width=2.4).move_to([-4.5, 0, 0])
            code = Node("Scoring code", color=TEAL, width=2.5).move_to([0, 0, 0])
            final = Node("Final list", color=TEAL, width=2.4).move_to([4.5, 0, 0])
            left = Link(tray, code, color=TEAL)
            right = Link(code, final, color=TEAL)
            agent = Agent(color=SAND).move_to([-4.5, 1.15, 0])
            conflict = Square(side_length=0.38, color=AMBER, fill_opacity=0.3).rotate(PI / 4).move_to([-6, -1.65, 0])
            branch = Arrow(conflict.get_right(), tray.get_bottom(), color=AMBER, buff=0.18)
            inspect = SurroundingRectangle(final, color=SAND, buff=0.2)
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), FadeIn(inbox_label), run_time=0.8)
            self.play(FadeIn(tray), FadeIn(agent), FadeIn(code), FadeIn(final), run_time=1.2)
            self.play(GrowArrow(left.arrow), GrowArrow(right.arrow), run_time=1.4)
            self.play(Create(conflict), GrowArrow(branch), run_time=1.4)
            self.play(Create(inspect), run_time=1)
            self.play(Transform(inspect, SurroundingRectangle(code, color=SAND, buff=0.2)), run_time=1.4)
            self.play(Transform(inspect, SurroundingRectangle(VGroup(tray, branch, conflict), color=AMBER, buff=0.18)), run_time=1.6)
        with self.beat("s05b02") as b:
            next_tag = Tag("author_interpretation")
            recommendation = T("Authors’ recommendations", size=25, color=SOFT).move_to([1.2, 2.1, 0])
            monitor = Panel(3.7, 1.1).move_to([-2.5, -2.1, 0])
            monitor_label = T("Reasoning monitor", size=24).move_to(monitor)
            trail = VMobject(color=SAND).set_points_as_corners([agent.get_right(), [-2.5, 1.15, 0], monitor.get_top()])
            argument = Node("Safety argument", color=SAND, width=3.4, height=1.1).move_to([2.5, -2.1, 0])
            self.play(ReplacementTransform(tag, next_tag), FadeOut(inspect), FadeIn(recommendation), run_time=1)
            tag = next_tag
            self.play(Create(trail), Create(monitor), run_time=2)
            self.play(FadeIn(monitor_label), run_time=1)
            self.play(Create(argument.box), FadeIn(argument.label), run_time=2)
            self.play(Indicate(monitor, color=SAND), Indicate(argument.box, color=SAND), run_time=1.5)
        with self.beat("s05b03") as b:
            next_tag = Tag("limitation")
            evidence_label = T("Constructed evidence", size=25).move_to([-2.7, 2.1, 0])
            deployment_label = T("Deployment remains open", size=22, color=SOFT).move_to([4.85, 2.1, 0])
            boundary = DashedLine([2.8, -2.8, 0], [2.8, 2.6, 0], color=SOFT)
            frame = RoundedRectangle(width=13, height=4.7, corner_radius=0.16, color=SAND).move_to([0, -0.1, 0])
            target_frame = RoundedRectangle(width=8.8, height=3.5, corner_radius=0.16, color=SAND).move_to([-1.8, -0.15, 0])
            goal = Square(side_length=0.38, color=TEAL, fill_opacity=0.3).move_to([-5, -2.45, 0])
            memo = Node("Situation memo", color=SAND, width=2.5, height=0.6, size=22).move_to([-1.4, -2.45, 0])
            goal_link = Arrow(goal.get_top(), tray.get_bottom(), color=TEAL, buff=0.15)
            memo_link = Arrow(memo.get_top(), code.get_bottom(), color=SAND, buff=0.15)
            self.play(ReplacementTransform(tag, next_tag), FadeOut(recommendation), FadeOut(inbox_label), FadeOut(trail), FadeOut(monitor), FadeOut(monitor_label), FadeOut(argument), run_time=1)
            tag = next_tag
            self.play(Create(frame), run_time=1.3)
            self.play(Transform(frame, target_frame), Create(boundary), FadeIn(evidence_label), FadeIn(deployment_label), run_time=2)
            self.play(Create(goal), FadeIn(memo), run_time=1.2)
            self.play(GrowArrow(goal_link), GrowArrow(memo_link), run_time=1.5)
        with self.beat("s05b04") as b:
            next_tag = Tag("author_interpretation")
            takeaway = T("Trace the process", size=28).move_to([0, 2.1, 0])
            tracer = Dot(tray.get_left(), radius=0.08, color=TEAL)
            self.play(ReplacementTransform(tag, next_tag), FadeOut(evidence_label), FadeOut(deployment_label), FadeOut(boundary), FadeOut(frame), FadeIn(takeaway), run_time=1)
            self.play(FadeIn(tracer), run_time=0.4)
            self.play(tracer.animate.move_to(tray.get_center()), run_time=1.5)
            self.play(Indicate(branch, color=AMBER), Indicate(conflict, color=AMBER), run_time=1.5)
            self.play(tracer.animate.move_to(code.get_center()), run_time=2)
            self.play(tracer.animate.move_to(final.get_center()), run_time=2)
            self.play(Indicate(goal, color=TEAL), Indicate(goal_link, color=TEAL), run_time=1.3)
            self.play(Indicate(conflict, color=AMBER), Indicate(branch, color=AMBER), run_time=1.3)
            self.play(FadeOut(tracer), run_time=0.5)
