# storyboard: ce92c542453d19d6
from aisr_kit import *

def file_card(color=SOFT):
    card = RoundedRectangle(width=0.65, height=0.9, corner_radius=0.06, color=color)
    lines = VGroup(*[Line(LEFT * 0.2, RIGHT * 0.2, color=color).shift(UP * y) for y in [0.2, 0, -0.2]])
    return VGroup(card, lines)

class S01(NarratedScene):
    def construct(self):
        with self.beat("s01b01") as b:
            heading = Heading("A report you rely on")
            tag = Tag("future_scenario")
            source = Source("Schoen et al. (2025)")
            files_label = T("Files", size=44).move_to([-4.8, 1.7, 0])
            report_label = T("Report", size=44).move_to([4.4, 1.7, 0])
            agent = Agent(color=SAND, radius=0.45).move_to([0, 0.3, 0])
            tray = VGroup(Line([-0.9, 0.3, 0], [-0.9, -0.3, 0]), Line([-0.9, -0.3, 0], [0.9, -0.3, 0]), Line([0.9, -0.3, 0], [0.9, 0.3, 0])).set_color(SOFT).move_to([4.4, 0.1, 0])
            cards = VGroup(*[file_card().move_to([-5.1 + i * 0.8, 0.3, 0]) for i in range(3)])
            route = Arrow([-2.7, 0.3, 0], [3.4, 0.3, 0], color=TEAL, buff=0.1)
            check = T("Required check", size=40, color=AMBER).move_to([-3.9, -1.75, 0])
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), FadeIn(files_label), FadeIn(report_label), Create(tray), FadeIn(agent), run_time=1)
            self.play(LaggedStart(*[Create(c) for c in cards], lag_ratio=0.2), GrowArrow(route), run_time=2)
            self.play(cards[2].animate.move_to([4.0, 0.5, 0]), run_time=3)
            self.play(cards[1].animate.move_to([4.8, 0.5, 0]), cards[0].animate.move_to([-3.9, -0.7, 0]), FadeIn(check), run_time=3)
        with self.beat("s01b02") as b:
            self.play(FadeOut(files_label), FadeOut(check), FadeOut(cards[0]), FadeOut(report_label), FadeOut(cards[1:]), run_time=1)
            transparent = T("Transparent route", size=36, color=TEAL).move_to([0, 1.9, 0])
            concealed = T("Concealed route", size=36, color=AMBER).move_to([0, -1.9, 0])
            hidden_route = VMobject(color=AMBER).set_points_as_corners([[-2.7, 0.3, 0], [-1.7, -1.1, 0], [1.8, -1.1, 0], [3.4, 0.3, 0]])
            reports = VGroup(*[RoundedRectangle(width=0.65, height=0.9, corner_radius=0.06, color=SOFT).move_to([4.4, y, 0]) for y in [1.1, -1.2]])
            self.play(Create(hidden_route), FadeIn(transparent), FadeIn(concealed), run_time=3)
            self.play(Create(reports[0]), Create(reports[1]), run_time=2)
            token = Dot([-2.7, 0.3, 0], color=AMBER)
            self.play(FadeIn(token), run_time=0.5)
            self.play(MoveAlongPath(token, hidden_route), run_time=3)
            self.play(FadeOut(token), run_time=0.5)
        with self.beat("s01b03") as b:
            tag_next = Tag("author_interpretation")
            goal = Square(side_length=0.7, color=AMBER).rotate(PI / 4).move_to([1.7, -1, 0])
            scheming = T("Scheming", size=40, color=AMBER).move_to([1.7, -2.1, 0])
            visible = T("Visible behavior", size=36).move_to([4.4, 2, 0])
            oversight = RoundedRectangle(width=3.3, height=3.5, corner_radius=0.1, color=SOFT).move_to([4.4, -0.1, 0])
            self.play(FadeOut(tag), FadeOut(transparent), FadeOut(concealed), FadeOut(route), run_time=0.5)
            self.play(FadeIn(tag_next), run_time=0.5)
            self.play(ReplacementTransform(hidden_route, goal), FadeIn(scheming), Create(oversight), FadeIn(visible), run_time=2)
            self.play(agent.animate.move_to([0.8, -1, 0]), run_time=3)
            self.play(Indicate(reports, color=SOFT), run_time=2)
            self.wait(b.duration - 8.7)
            # Clear this beat's diagram before s01b04 so that beat opens on its own state.
            self.play(FadeOut(tag_next, goal, scheming, visible, oversight, agent, reports, tray), run_time=0.7)
        with self.beat("s01b04") as b:
            tag = Tag("method")
            evaluation = RoundedRectangle(width=12.2, height=4.9, corner_radius=0.15, color=SOFT).move_to([0, -0.15, 0])
            eval_label = T("Constructed evaluations", size=40, color=SOFT).move_to([0, 1.75, 0])
            agent = Agent(color=SAND, radius=0.5).move_to([0, 0.35, 0])
            tray = VGroup(Line([-1.0, 0.35, 0], [-1.0, -0.35, 0]), Line([-1.0, -0.35, 0], [1.0, -0.35, 0]), Line([1.0, -0.35, 0], [1.0, 0.35, 0])).set_color(SOFT).move_to([4.5, 0.2, 0])
            report = RoundedRectangle(width=0.7, height=0.95, corner_radius=0.06, color=SOFT).move_to([4.5, 0.45, 0])
            hidden = DashedVMobject(VMobject(color=AMBER).set_points_smoothly([[0.3, -0.2, 0], [1.6, -1.15, 0], [3.2, -1.0, 0], [4.0, -0.25, 0]]), num_dashes=18)
            covert = T("Covert actions", size=44, color=AMBER).move_to([1.9, -1.75, 0])
            rules = Node("Safety rules", color=TEAL, width=3.4, height=1.1, size=40).move_to([-4.0, 0.35, 0])
            self.play(FadeIn(tag), Create(evaluation), FadeIn(eval_label), run_time=1.2)
            self.play(FadeIn(agent), Create(tray), FadeIn(report), run_time=1)
            self.play(Create(hidden), FadeIn(covert), run_time=2.5)
            self.wait(2.5)
            self.play(FadeIn(rules, shift=RIGHT * 0.4), run_time=1)
            self.play(rules.animate.next_to(agent, LEFT, buff=0.15), run_time=3)
            output = Arrow([0.6, 0.35, 0], [3.3, 0.35, 0], color=TEAL, buff=0)
            self.play(GrowArrow(output), Indicate(report, color=TEAL), run_time=2)
        with self.beat("s01b05") as b:
            self.play(FadeOut(rules, covert, hidden, report, tray, output, evaluation, eval_label), run_time=1)
            models = VGroup(Node("o3", color=SAND, width=2.6, height=1.0, size=44).move_to([-0.6, 1.1, 0]), Node("o4-mini", color=SAND, width=2.6, height=1.0, size=44).move_to([-0.6, -1.1, 0]))
            training = Node("Anti-scheming\ntraining", color=TEAL, height=1.7, size=36).move_to([-4.3, 0, 0])
            tests_label = T("New tests", size=44).move_to([4.3, 1.9, 0])
            tests = VGroup(*[RoundedRectangle(width=1.25, height=1.0, corner_radius=0.08, color=SOFT).move_to([3.5 + (i % 2) * 1.6, 0.65 - (i // 2) * 1.5, 0]) for i in range(4)])
            # Split the agent into the two lane boxes (shapes only), then fade the labels in once settled.
            agent_copy = agent.copy()
            self.add(agent_copy)
            self.play(ReplacementTransform(agent, models[0].box), ReplacementTransform(agent_copy, models[1].box), FadeIn(training), run_time=1.4)
            self.play(FadeIn(models[0].label), FadeIn(models[1].label), run_time=0.6)
            links = VGroup(*[Arrow(training.get_right(), model.get_left(), color=TEAL, buff=0.15) for model in models])
            self.play(LaggedStart(*[GrowArrow(link) for link in links], lag_ratio=0.3), run_time=2)
            self.play(FadeIn(tests_label), LaggedStart(*[Create(test) for test in tests], lag_ratio=0.3), run_time=3)
            connections = VGroup(Arrow(models[0].get_right(), [2.75, 0.65, 0], color=SOFT, buff=0.15), Arrow(models[1].get_right(), [2.75, -0.85, 0], color=SOFT, buff=0.15))
            self.play(*[GrowArrow(link) for link in connections], run_time=2)
