# storyboard: 66915a2d12446231
from aisr_kit import *

class S02(NarratedScene):
    def construct(self):
        with self.beat('s02b01') as b:
            heading = Heading('Learning transparent actions')
            tag = Tag('method')
            source = Source('Schoen et al. (2025)')
            rule = Node('Safety specification', color=TEAL, width=3.7, size=26).move_to(LEFT*4 + UP*0.7)
            agent = Agent(color=SAND, radius=0.38).move_to(LEFT*0.5)
            thought = Panel(3.6, 1.1, color=TEAL).move_to(UP*1.8 + RIGHT*0.3)
            thought_label = T('Reason before acting', size=26, color=TEAL).move_to(thought)
            principle = Circle(radius=0.13, color=TEAL, fill_opacity=1).move_to(UP*1.8 + LEFT*1.1)
            file = Rectangle(width=1.0, height=1.4, color=SOFT).move_to(RIGHT*3.7)
            lines = VGroup(*[Line(LEFT*0.3, RIGHT*0.3, color=MUTED).move_to(file.get_center()+UP*y) for y in [0.3,0,-0.3]])
            title = T('Deliberative alignment', size=30).move_to(DOWN*2.3)
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), Create(rule.box), FadeIn(rule.label), run_time=2)
            self.play(FadeIn(agent), FadeIn(title), run_time=1)
            token = Circle(radius=0.13, color=TEAL, fill_opacity=1).move_to(rule.get_center())
            self.play(FadeIn(token), run_time=0.5)
            self.play(token.animate.move_to(agent), run_time=1.5)
            self.play(Create(thought), FadeIn(thought_label), FadeOut(token), run_time=1.5)
            self.play(Create(file), Create(lines), run_time=1)
            self.play(agent.animate.move_to(RIGHT*2.6), run_time=2)
            self.play(VGroup(file,lines).animate.shift(RIGHT*0.8), run_time=1)
        with self.beat('s02b02') as b:
            self.play(FadeOut(title), FadeOut(file), FadeOut(lines), agent.animate.move_to(RIGHT*2.3+DOWN*0.3), run_time=1)
            prompt = Panel(4.5,2.6).move_to(LEFT*3.6+DOWN*0.4)
            prompt_label = T('Prompt', size=26).move_to(LEFT*3.6+DOWN*1.35)
            training = Panel(3.0,2.2,color=TEAL).move_to(RIGHT*2.3+DOWN*0.3)
            examples = VGroup(*[Rectangle(width=1.0,height=0.7,color=TEAL).move_to(LEFT*3.6+DOWN*0.4+RIGHT*x) for x in [-0.7,0,0.7]])
            example_label = T('Example reasoning', size=26,color=TEAL).move_to(DOWN*2.25+LEFT*3.6)
            recall = T('Recall rules',size=26,color=TEAL).move_to(thought)
            self.play(Create(prompt),FadeIn(prompt_label),Create(training),agent.animate.set_opacity(1),run_time=1)
            self.bring_to_front(agent)
            self.play(rule.animate.shift(UP*0.5),Create(examples),FadeIn(example_label),run_time=1.5)
            for example in examples:
                self.play(example.animate.move_to(training.get_center()).set_opacity(0),run_time=1)
            self.play(rule.animate.shift(LEFT*2+UP*0.5).set_opacity(0),Transform(thought_label,recall),run_time=2)
            self.play(FadeIn(principle),run_time=1)
        with self.beat('s02b03') as b:
            self.play(FadeOut(prompt),FadeOut(prompt_label),FadeOut(example_label),FadeOut(examples),FadeOut(training),agent.animate.move_to(LEFT*2.5+DOWN*0.3),run_time=1.5)
            action = Node('Action',color=TEAL,width=2.7).move_to(RIGHT*2.5+DOWN*0.3)
            feedback = T('Outcome feedback',size=26,color=TEAL).move_to(DOWN*2.15)
            rl = T('Reinforcement learning',size=30).move_to(UP*0.8)
            top_arrow = CurvedArrow(LEFT*2.1+DOWN*0.1,RIGHT*1.1+DOWN*0.1,angle=-TAU/5,color=TEAL)
            low_arrow = CurvedArrow(RIGHT*2.4+DOWN*0.9,LEFT*2.4+DOWN*0.9,angle=-TAU/4,color=TEAL)
            self.play(Create(action.box),FadeIn(action.label),FadeIn(rl),run_time=1)
            self.play(Create(top_arrow),run_time=2)
            moving = Circle(radius=0.12,color=TEAL,fill_opacity=1).move_to(top_arrow.get_start())
            self.play(FadeIn(moving),MoveAlongPath(moving,top_arrow),run_time=2)
            self.play(Create(low_arrow),FadeIn(feedback),run_time=1.5)
            self.play(moving.animate.move_to(low_arrow.get_start()),run_time=0.5)
            self.play(MoveAlongPath(moving,low_arrow),run_time=2)
            self.play(FadeOut(moving),Indicate(action.box,color=TEAL),run_time=1)
        with self.beat('s02b04') as b:
            self.play(FadeOut(action.label), FadeOut(feedback), FadeOut(rl), FadeOut(thought_label), run_time=0.5)
            old = VGroup(action.box,top_arrow,low_arrow,thought,principle)
            self.play(old.animate.scale(0.3).move_to(LEFT*5.3+UP*0.8),agent.animate.move_to(LEFT*5.3+DOWN*0.5),run_time=2)
            labels=['Software tasks','Corporate scenarios','Games']
            centers=[LEFT*2.4,RIGHT*1.0,RIGHT*4.4]
            boxes=VGroup(*[Panel(3.0,2.5).move_to(p) for p in centers])
            captions=VGroup(*[T(text,size=24).move_to(p+DOWN*1.8) for text,p in zip(labels,centers)])
            doc=Rectangle(width=0.8,height=1.2,color=SOFT).move_to(centers[0])
            doclines=VGroup(*[Line(LEFT*0.24,RIGHT*0.24,color=TEAL).move_to(centers[0]+UP*y) for y in [-0.3,0,0.3]])
            gauge=Arc(radius=0.7,start_angle=0,angle=PI,color=SOFT).move_to(centers[1])
            needle=Line(centers[1]+DOWN*0.25,centers[1]+UP*0.35+RIGHT*0.4,color=TEAL)
            grid=Grid(3,3,cell=0.4).move_to(centers[2])
            self.play(LaggedStart(*[Create(box) for box in boxes],lag_ratio=0.2),FadeIn(captions),run_time=2)
            self.play(Create(doc),Create(doclines),Create(gauge),Create(needle),Create(grid),run_time=2)
            self.bring_to_front(agent)
            new=T('New situations',size=30,color=TEAL).move_to(UP*2.1)
            self.play(FadeIn(new),agent.animate.set_opacity(1).move_to(centers[0]+DOWN*0.6),run_time=2)
            self.play(agent.animate.move_to(centers[1]+DOWN*0.6),needle.animate.rotate(-PI/3,about_point=needle.get_start()),run_time=2)
            self.play(agent.animate.move_to(grid.cell(2,0).get_center()),run_time=2)
        with self.beat('s02b05') as b:
            self.play(FadeOut(old),FadeOut(boxes),FadeOut(captions),FadeOut(doc),FadeOut(doclines),FadeOut(gauge),FadeOut(needle),FadeOut(grid),FadeOut(agent),FadeOut(new),Transform(tag,Tag('limitation')),run_time=1.5)
            gate=Panel(3.3,3.0,color=SOFT).move_to(LEFT*0.2)
            gate_label=T('Manual verification',size=26).move_to(UP*2.1)
            reasoning=Node('Reasoning',color=TEAL,width=2.8).move_to(RIGHT*3.8+UP*1.0)
            behavior=T('Behavior',size=26).move_to(LEFT*4.8+UP*1.1)
            covert=Rectangle(width=0.9,height=0.65,color=AMBER,fill_opacity=0.15).move_to(LEFT*4.8+DOWN*0.1)
            ambiguous=Rectangle(width=0.9,height=0.65,color=SAND,fill_opacity=0.15).move_to(LEFT*4.8+DOWN*1.2)
            tray=VGroup(Line(LEFT*0.8,RIGHT*0.8,color=SOFT),Line(LEFT*0.8,LEFT*0.8+UP*0.3,color=SOFT),Line(RIGHT*0.8,RIGHT*0.8+UP*0.3,color=SOFT)).move_to(RIGHT*3.8+DOWN*1.65)
            link=Line(gate.get_right()+UP*0.7,reasoning.get_left(),color=TEAL)
            undercount=T('Possible undercounting',size=30,color=AMBER).move_to(DOWN*2.6)
            self.play(Create(gate),FadeIn(gate_label),Create(reasoning.box),FadeIn(reasoning.label),FadeIn(behavior),Create(link),run_time=2)
            self.play(Create(covert),Create(ambiguous),Create(tray),run_time=1.5)
            self.play(covert.animate.move_to(LEFT*0.2+UP*0.45),ambiguous.animate.move_to(LEFT*0.2+DOWN*0.7),run_time=2)
            self.play(Indicate(reasoning.box,color=TEAL),run_time=1.5)
            self.play(ambiguous.animate.move_to(RIGHT*3.8+DOWN*1.25),run_time=2)
            self.play(Indicate(covert,color=AMBER),FadeIn(undercount),run_time=2)
