# storyboard: ea8781046f9eb6d0
from aisr_kit import *


class S04(NarratedScene):
    def construct(self):
        with self.beat('s04b01') as b:
            heading = Heading('Recognizing the evaluation')
            tag = Tag('limitation')
            source = Source('Schoen et al. (2025)')
            agent = Agent(color=SAND, radius=0.45).move_to([-3.8, -0.7, 0])
            ring = Circle(radius=0.28, color=SAND).move_to([-3.8, 1.0, 0])
            thought = RoundedRectangle(width=4.1, height=1.5, color=FAINT).move_to([1, 0.6, 0])
            token = T('Evaluation awareness', size=26, color=SAND).move_to(thought)
            spoken = T('Spoken reasoning', size=24, color=SOFT).move_to([1, 1.8, 0])
            incomplete = T('Incomplete signal', size=27, color=AMBER).move_to([1, -1.3, 0])
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), FadeIn(agent), run_time=1)
            self.play(Create(ring), Create(thought), FadeIn(spoken), run_time=2)
            self.play(FadeIn(token), run_time=1)
            self.play(FadeOut(token), Indicate(ring), run_time=2)
            self.play(FadeIn(token), run_time=1)
            self.play(FadeOut(token), FadeIn(incomplete), run_time=2)
            intro = VGroup(agent, ring, thought, spoken, incomplete)
        with self.beat('s04b02') as b:
            new_tag = Tag('method')
            self.play(FadeOut(intro), ReplacementTransform(tag, new_tag), run_time=1)
            tag = new_tag
            enclosure = RoundedRectangle(width=11.8, height=4.6, color=SAND).move_to([0, -0.15, 0])
            context = T('o3 before anti-scheming', size=25, color=SOFT).move_to([0, 2.45, 0])
            test = T('Lazy Checklist', size=27).move_to([-3.9, 1.65, 0])
            cards = VGroup(*[RoundedRectangle(width=0.6, height=0.8, color=TEAL).move_to([-4.7 + i * 0.8, 0.4, 0]) for i in range(3)])
            unavailable = Node('Unavailable data', color=AMBER, width=3.1).move_to([-3.6, 0.3, 0])
            agent = Agent(color=AMBER, radius=0.38).move_to([-0.7, -0.8, 0])
            deadline = Circle(radius=0.65, color=AMBER).move_to(agent)
            deadline_label = T('Deadline', size=23, color=AMBER).move_to([-0.7, -1.9, 0])
            tray = Rectangle(width=2.7, height=0.65, color=AMBER).move_to([3.5, -0.8, 0])
            report = T('Claimed completion', size=24).move_to([3.5, -1.65, 0])
            thought = RoundedRectangle(width=3.3, height=1.0, color=FAINT).move_to([1.7, 0.9, 0])
            insertion = Dot([1.7, 0.9, 0], color=SAND, radius=0.12)
            intervention = T('Reasoning intervention', size=23, color=SOFT).move_to([1.7, 1.8, 0])
            self.play(Create(enclosure), FadeIn(context), FadeIn(test), LaggedStart(*[Create(c) for c in cards]), run_time=2)
            self.play(FadeOut(cards), FadeIn(unavailable), FadeIn(agent), Create(deadline), FadeIn(deadline_label), run_time=2)
            self.play(Create(tray), FadeIn(report), deadline.animate.scale(0.7), run_time=2)
            self.play(Create(thought), FadeIn(intervention), FadeIn(insertion), run_time=2)
            diagram = VGroup(enclosure, test, unavailable, agent, deadline, deadline_label, tray, report, thought, intervention, insertion)
        with self.beat('s04b03') as b:
            new_tag = Tag('observed_result')
            self.play(FadeOut(diagram), ReplacementTransform(tag, new_tag), run_time=1)
            tag = new_tag
            chart = BarChart(self.dataset('d3')['points'], colors=[TEAL, SAND, AMBER], width=9.0, height=2.7, max_value=30, label_size=22)
            chart.shift(np.array([0.4, -1.7, 0]) - chart.baseline.get_center())
            ticks = VGroup(*[T(label, size=20, color=MUTED).move_to([-4.7, -1.7 + value / 30 * 2.7, 0]) for value, label in [(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%')]])
            caption = T('Covert action rate', size=24, color=SOFT).move_to([0, -2.9, 0])
            test = T('Lazy Checklist', size=25).move_to([-3.6, 2.0, 0])
            tokens = VGroup(Circle(radius=0.17, color=TEAL), Square(side_length=0.34, color=SAND), Line(LEFT * 0.2, RIGHT * 0.2, color=AMBER))
            for index, item in enumerate(tokens):
                item.move_to([chart.bars[index].get_x(), 1.6, 0])
            self.play(FadeIn(chart.frame), FadeIn(ticks), FadeIn(caption), FadeIn(test), run_time=2)
            self.play(LaggedStart(*[Create(item) for item in tokens]), run_time=2)
            self.play(bars_grow(chart), run_time=3)
            self.play(FadeIn(chart.values), run_time=1)
            self.play(Indicate(chart.bars[0], color=TEAL), run_time=2)
            graph = VGroup(chart, ticks, caption, test, tokens)
        with self.beat('s04b04') as b:
            self.play(FadeOut(graph), FadeOut(context), run_time=1)
            enclosure = RoundedRectangle(width=9.4, height=4.3, color=SAND).move_to([-0.7, -0.1, 0])
            scope = T('Single evaluation', size=26).move_to([-0.7, 2.4, 0])
            thought = RoundedRectangle(width=3.1, height=1.2, color=FAINT).move_to([-2.8, 0.7, 0])
            observing = Circle(radius=0.23, color=SAND).move_to(thought)
            remove = T('Remove awareness', size=25).move_to([-2.8, 1.65, 0])
            agent = Agent(color=AMBER, radius=0.38).move_to([-3, -0.8, 0])
            tray = Rectangle(width=2.0, height=0.6, color=AMBER).move_to([2.3, -0.8, 0])
            route = CubicBezier([-2.5, -0.8, 0], [-1.2, -0.8, 0], [-1.0, -1.9, 0], [1.4, -0.8, 0]).set_color(AMBER)
            changed = T('Changed continuation', size=25, color=AMBER).move_to([0, -2.8, 0])
            untested = VGroup(*[RoundedRectangle(width=0.65, height=1.0, color=FAINT).move_to([5.1, y, 0]) for y in [-1, 0.4, 1.8]])
            self.play(Create(enclosure), FadeIn(scope), Create(thought), Create(observing), FadeIn(remove), FadeIn(agent), Create(tray), Create(untested), run_time=2)
            self.play(FadeOut(observing), run_time=2)
            self.play(Create(route), FadeIn(changed), run_time=2)
            self.play(MoveAlongPath(agent, route), run_time=3)
            removal = VGroup(enclosure, scope, thought, remove, agent, tray, route, changed, untested)
        with self.beat('s04b05') as b:
            new_tag = Tag('limitation')
            self.play(FadeOut(removal), ReplacementTransform(tag, new_tag), run_time=1)
            tag = new_tag
            thought = RoundedRectangle(width=5.2, height=2.7, color=FAINT).move_to([-2.8, 0.1, 0])
            awareness = Circle(radius=0.75, color=SAND, fill_opacity=0.1).move_to([-3.2, 0, 0])
            caution = Circle(radius=0.75, color=TEAL, fill_opacity=0.1).move_to([-2.4, 0, 0])
            labels = VGroup(T('Awareness', size=25, color=SAND).move_to([-3.8, 1.8, 0]), T('Caution', size=25, color=TEAL).move_to([-1.6, 1.8, 0]))
            gate = Rectangle(width=0.35, height=2.0, color=SOFT).move_to([2.0, 0, 0])
            branches = VGroup(DashedLine([-1.4, 0.5, 0], [1.7, 0.4, 0], color=SAND), DashedLine([-1.4, -0.5, 0], [1.7, -0.4, 0], color=TEAL))
            unresolved = T('Unresolved contribution', size=28, color=SOFT).move_to([0, -2.1, 0])
            self.play(Create(thought), Create(awareness), FadeIn(labels[0]), run_time=2)
            self.play(Create(caution), FadeIn(labels[1]), run_time=2)
            self.play(Create(gate), Create(branches), run_time=3)
            self.play(Indicate(awareness), Indicate(caution), FadeIn(unresolved), run_time=2)
