# storyboard: 37901d4987c33d6e
from aisr_kit import *

class S05(NarratedScene):
    def construct(self):
        with self.beat("s05b01") as b:
            heading = Heading("Testing durability")
            tag = Tag("method")
            source = Source("Schoen et al. (2025)")
            agent = Agent(color=SAND, radius=0.5).move_to(LEFT * 4)
            name = T("o4-mini", size=24).next_to(agent, DOWN, buff=0.35)
            goal = Square(side_length=0.3, color=AMBER, fill_opacity=0.8).rotate(PI/4).move_to(LEFT * 5.5 + UP)
            goal_label = T("Inserted sabotage goal", size=24).move_to(LEFT * 3.8 + UP * 2)
            enclosure = RoundedRectangle(width=3.5, height=2.2, color=FAINT).move_to(RIGHT * 3.9)
            successor = Node("Hypothetical\nsuccessor", color=SAND, width=2.7, height=1.2, size=24).move_to(enclosure)
            gate = RoundedRectangle(width=0.6, height=2.2, color=TEAL).move_to(ORIGIN)
            gate_label = T("Anti-scheming training", size=24).move_to(DOWN * 1.9)
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), FadeIn(agent), FadeIn(name), Create(enclosure), FadeIn(successor), run_time=2)
            self.play(FadeIn(goal_label), FadeIn(goal), run_time=1)
            self.play(goal.animate.move_to(agent), run_time=2)
            self.play(Create(gate), FadeIn(gate_label), run_time=1)
            self.play(VGroup(agent, goal).animate.move_to(RIGHT * 1.3), FadeOut(name), run_time=3)
            self.play(agent.animate.set_color(TEAL), run_time=1)
        with self.beat("s05b02") as b:
            next_tag = Tag("observed_result")
            self.play(ReplacementTransform(tag, next_tag), FadeOut(VGroup(agent, goal, goal_label, enclosure, successor, gate, gate_label)), run_time=1)
            tag = next_tag
            data = self.dataset("d4")
            chart = BarChart(data["points"], colors=[AMBER], width=5, height=2.7, max_value=1, unit=data["unit"], label_size=22).move_to(LEFT * 3 + DOWN * 0.25)
            title = T("RL Sabotage", size=26).move_to(LEFT * 3 + UP * 2.1)
            card = Node("Correct response", color=TEAL, width=3.5, height=1.2).move_to(RIGHT * 3 + UP * 0.7)
            wrong = T("Incorrect grade", size=26, color=AMBER).move_to(RIGHT * 3 + DOWN * 0.5)
            token = Square(side_length=0.3, color=AMBER, fill_opacity=0.8).rotate(PI/4).move_to(RIGHT * 3 + DOWN * 1.3)
            cases = T("5 cases", size=24, color=AMBER).move_to(RIGHT * 3 + DOWN * 2)
            count = T("6 out of 2800", size=24).move_to(LEFT * 3 + DOWN * 2.7)
            scale_bottom = chart.baseline.get_start()
            scale_top = scale_bottom + UP * 2.7
            scale = VGroup(Line(scale_bottom, scale_top, color=FAINT), T("0%", size=20).next_to(scale_bottom, LEFT, buff=0.15), T("1%", size=20).next_to(scale_top, LEFT, buff=0.15))
            context = T("Hypothetical successor", size=24).move_to(RIGHT * 3 + UP * 1.7)
            self.play(FadeIn(title), FadeIn(chart.frame), FadeIn(scale), FadeIn(context), run_time=1)
            self.play(bars_grow(chart), run_time=3)
            self.play(FadeIn(chart.values), FadeIn(count), FadeIn(card), run_time=1)
            self.play(FadeIn(wrong), Indicate(card.box, color=AMBER), run_time=2)
            self.play(FadeIn(token), FadeIn(cases), run_time=1)
        with self.beat("s05b03") as b:
            next_tag = Tag("method")
            self.play(ReplacementTransform(tag, next_tag), FadeOut(VGroup(chart, title, card, wrong, token, cases, count, scale, context)), run_time=1)
            tag = next_tag
            agent = Agent(color=TEAL, radius=0.5).move_to(LEFT * 4)
            safety = Circle(radius=0.16, color=SAND, fill_opacity=0).move_to(agent)
            tasks = Node("Coding\nInstruction following", color=SAND, width=3.6, height=1.5, size=24).move_to(UP * 0.7)
            reward = Node("Outcome rewards", color=TEAL, width=3.1, size=24).move_to(RIGHT * 4 + DOWN * 0.7)
            loop_title = T("Capability training", size=28).move_to(UP * 2.2)
            to_tasks = Link(agent, tasks, color=TEAL)
            to_reward = Link(tasks, reward, color=TEAL)
            feedback = Arrow(reward.get_bottom(), agent.get_bottom(), path_arc=-PI/3, color=TEAL, buff=0.2)
            self.play(FadeIn(agent), FadeIn(safety), FadeIn(loop_title), run_time=1)
            self.play(FadeIn(tasks), GrowArrow(to_tasks.arrow), run_time=2)
            self.play(FadeIn(reward), GrowArrow(to_reward.arrow), run_time=2)
            self.play(Create(feedback), run_time=2)
            self.play(Indicate(safety), Indicate(reward.box), run_time=2)
            loop = VGroup(tasks, reward, loop_title, to_tasks, to_reward, feedback)
        with self.beat("s05b04") as b:
            next_tag = Tag("observed_result")
            self.play(ReplacementTransform(tag, next_tag), FadeOut(loop), FadeOut(VGroup(agent, safety)), run_time=1)
            tag = next_tag
            before_title = T("Before later training", size=26).move_to(LEFT * 3 + UP * 2.1)
            after_title = T("After later training", size=26).move_to(RIGHT * 3 + UP * 2.1)
            before = VGroup(*[RoundedRectangle(width=1.3, height=0.75, color=FAINT) for i in range(3)]).arrange(DOWN, buff=0.3).move_to(LEFT * 3)
            after = before.copy().move_to(RIGHT * 3)
            shield_before = Arc(radius=1.7, start_angle=-PI/3, angle=PI*1.7, color=TEAL).move_to(LEFT * 3)
            shield_after = shield_before.copy().move_to(RIGHT * 3)
            marks = VGroup(*[Circle(radius=0.09, color=AMBER, fill_opacity=1).move_to(tray) for tray in after])
            small = T("Small increases", size=26, color=AMBER).move_to(DOWN * 2.5)
            self.play(FadeIn(before_title), FadeIn(after_title), Create(before), Create(after), Create(shield_before), Create(shield_after), run_time=2)
            self.play(LaggedStart(*[FadeIn(mark, shift=LEFT * 0.4) for mark in marks], lag_ratio=0.6), run_time=3)
            shorter = Arc(radius=1.7, start_angle=-PI/3, angle=PI*1.5, color=TEAL).move_to(RIGHT * 3)
            self.play(Transform(shield_after, shorter), FadeIn(small), run_time=2)
            comparison = VGroup(before_title, after_title, before, after, shield_before, shield_after, marks, small)
        with self.beat("s05b05") as b:
            next_tag = Tag("limitation")
            self.play(ReplacementTransform(tag, next_tag), FadeOut(comparison), run_time=1)
            task = Node("Training tasks", color=SAND, width=3).move_to(LEFT * 4 + UP * 0.5)
            opportunities = Node("Reward opportunities", color=TEAL, width=3.4, size=24).move_to(UP * 0.5)
            action = Node("Covert action", color=AMBER, width=2.8).move_to(RIGHT * 4 + UP * 0.5)
            known = Link(task, opportunities, color=SOFT)
            unknown = DashedLine(opportunities.get_right(), action.get_left(), color=AMBER, dash_length=0.13)
            hacking = T("Reward hacking", size=26).move_to(UP * 2)
            unresolved = T("Specific contribution unresolved", size=28, color=SOFT).move_to(DOWN * 1.6)
            self.play(FadeIn(task), FadeIn(opportunities), FadeIn(action), GrowArrow(known.arrow), run_time=2)
            self.play(Create(unknown), FadeIn(hacking), run_time=2)
            self.play(FadeIn(unresolved), Indicate(unknown, color=AMBER), run_time=2)
