# storyboard: e430f09e8505761e
from aisr_kit import *

class S01(NarratedScene):
    def construct(self):
        with self.beat("s01b01") as b:
            heading = Heading("A machine that keeps correcting")
            tag = Tag("future_scenario")
            corridor = VGroup(Line([-5.7, 1.5, 0], [5.7, 1.5, 0], color=FAINT), Line([-5.7, -1.4, 0], [5.7, -1.4, 0], color=FAINT))
            robot = Agent(color=BLUE).move_to([-5, 0, 0])
            person = VGroup(Circle(radius=.2, color=SAND), Line([0,-.25,0],[0,-.8,0],color=SAND), Line([-.3,-.45,0],[.3,-.45,0],color=SAND)).move_to([-1,1.8,0])
            goal = Circle(radius=.44, color=AMBER).move_to([4.8,.75,0])
            robot_label = T("Delivery robot", size=40, weight=SEMIBOLD).move_to([-4.3,-2.1,0])
            goal_label = T("Destination", size=40, color=AMBER, weight=SEMIBOLD).move_to([4.5,2.15,0])
            route = CubicBezier([-5,0,0],[-2,-1.6,0],[1,-1.3,0],[4.8,.75,0]).set_stroke(BLUE,2)
            self.play(FadeIn(heading),FadeIn(tag),Create(corridor),FadeIn(robot),Create(goal),FadeIn(robot_label),FadeIn(goal_label),run_time=1.5)
            self.play(FadeIn(person),person.animate.move_to([-1,0,0]),run_time=2)
            self.play(Create(route),MoveAlongPath(robot,route),run_time=5)
        with self.beat("s01b02") as b:
            set_label = T("Set destination",size=40,color=AMBER,weight=SEMIBOLD).move_to([4.1,2.15,0])
            intended = Rectangle(width=.85,height=1.05,color=SAND).move_to([4.8,-2,0])
            intended_label = T("Intended room",size=40,color=SAND,weight=SEMIBOLD).move_to([1.9,-2.1,0])
            self.play(FadeOut(goal_label),FadeOut(robot_label),robot.animate.move_to([-5,0,0]),run_time=0.6)
            self.play(FadeIn(set_label),Create(intended),FadeIn(intended_label),run_time=1.4)
            self.play(MoveAlongPath(robot,route),run_time=5)
            self.play(Indicate(goal,color=AMBER),run_time=1)
        with self.beat("s01b03") as b:
            tag_next=Tag("background")
            focused_goal=Circle(radius=.44,color=AMBER).move_to([1.6,.6,0])
            focused_route=CubicBezier([-4,0,0],[-2,-1.3,0],[0,-.8,0],[1.6,.6,0]).set_stroke(BLUE,2)
            label=T("Goal-directed behavior",size=32).move_to([-.7,2,0])
            self.play(FadeOut(tag),FadeIn(tag_next),FadeOut(corridor),FadeOut(person),FadeOut(set_label),Transform(goal,focused_goal),Transform(route,focused_route),robot.animate.move_to([-4,0,0]),intended.animate.move_to([4.8,-1.8,0]),intended_label.animate.move_to([2.4,-2.7,0]),FadeIn(label),run_time=2)
            tag=tag_next
            self.play(MoveAlongPath(robot,focused_route),run_time=4)
            self.play(Indicate(goal,color=AMBER),run_time=1)
            self.wait(b.duration-8.2)
            self.play(FadeOut(VGroup(tag,label,route,intended,intended_label)),run_time=0.8)
        with self.beat("s01b04") as b:
            tag=Tag("method")
            box=Rectangle(width=2.5,height=1.4,color=BLUE,fill_color=BLUE,fill_opacity=.12).move_to([0,0,0])
            box_label=T("Behavior",size=32,weight=SEMIBOLD).move_to(box)
            organism=Circle(radius=.45,color=BLUE).move_to([-5,0,0])
            machine=Square(side_length=.9,color=BLUE).move_to([5,0,0])
            organism_label=T("Organism",size=36,color=BLUE).move_to([-5,-.95,0])
            machine_label=T("Machine",size=36,color=BLUE).move_to([5,-.95,0])
            goal_label=T("Goal",size=36,color=AMBER).move_to([2.4,.95,0])
            title=Serif("Behavior, Purpose and Teleology",size=40).move_to([0,2,0])
            date=T("January 1943",size=34,color=SOFT).move_to([0,-2.1,0])
            source=Source("Rosenblueth et al. (1943)")
            self.play(FadeIn(tag),ReplacementTransform(robot,organism),Create(box),Create(machine),goal.animate.move_to([2.4,0,0]),FadeIn(title),FadeIn(date),FadeIn(source),run_time=2.5)
            self.play(FadeIn(organism_label),FadeIn(machine_label),FadeIn(box_label),FadeIn(goal_label),run_time=1.5)
            self.play(VGroup(organism,organism_label).animate.shift(RIGHT*.3),VGroup(machine,machine_label).animate.shift(LEFT*.3),run_time=2)
            self.play(Indicate(box,color=BLUE),Indicate(goal,color=AMBER),run_time=2)
        with self.beat("s01b05") as b:
            tag_next=Tag("definition")
            input_arrow=Arrow([-4,0,0],[-1.35,0,0],color=BLUE,buff=.1)
            output_arrow=Arrow([1.35,0,0],[3.55,0,0],color=BLUE,buff=.1)
            return_path=VMobject().set_points_as_corners([[3.9,-.5,0],[3.9,-1.35,0],[0,-1.35,0],[0,-.75,0]]).set_stroke(TEAL,3)
            return_tip=Triangle(color=TEAL,fill_opacity=1).scale(.12).move_to([0,-.75,0])
            purpose=T("Purpose",size=27,color=AMBER).move_to([3.9,.9,0])
            feedback=T("Feedback",size=27,color=TEAL).move_to([1.8,-1.9,0])
            prediction=T("Prediction",size=27,color=SOFT).move_to([5.4,1.8,0])
            future=Circle(radius=.44,color=AMBER,stroke_opacity=.35).move_to([5.4,0,0])
            self.play(FadeOut(tag),FadeIn(tag_next),FadeOut(organism),FadeOut(machine),FadeOut(organism_label),FadeOut(machine_label),FadeOut(goal_label),FadeOut(title),FadeOut(date),goal.animate.move_to([3.9,0,0]),run_time=1.5)
            self.play(GrowArrow(input_arrow),GrowArrow(output_arrow),FadeIn(purpose),run_time=2)
            self.play(Create(return_path),FadeIn(return_tip),FadeIn(feedback),run_time=2)
            self.play(Create(future),FadeIn(prediction),run_time=2)
