# storyboard: debd31b6a6bd61b4
from aisr_kit import *

class S02(NarratedScene):
    def construct(self):
        with self.beat("s02b01") as b:
            heading = Heading("What counts as purpose")
            tag = Tag("method")
            source = Source("Rosenblueth et al. (1943)")
            obj = Node("Object", color=BLUE, width=2.7, height=1.8).move_to(ORIGIN)
            inp = T("Input").move_to(LEFT*4.5+UP*0.8)
            out = T("Output").move_to(RIGHT*4.5+UP*0.8)
            ia = Arrow(LEFT*5.5, LEFT*1.5, color=SOFT, buff=0)
            oa = Arrow(RIGHT*1.5, RIGHT*5.5, color=SOFT, buff=0)
            circuit = VGroup(Line(LEFT*.9+DOWN*.45, DOWN*.45, color=MUTED), Line(DOWN*.45, RIGHT*.9+DOWN*.15, color=MUTED))
            pulse = Dot(LEFT*5.5, color=BLUE, radius=.13)
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), FadeIn(obj), FadeIn(inp), FadeIn(out), Create(circuit), run_time=1)
            self.play(GrowArrow(ia), GrowArrow(oa), run_time=1.5)
            self.play(FadeIn(pulse), run_time=.3)
            self.play(pulse.animate.move_to(RIGHT*5.5), FadeOut(circuit), ia.animate.set_color(BLUE), oa.animate.set_color(BLUE), run_time=4)
            self.play(FadeOut(pulse), run_time=.3)
        with self.beat("s02b02") as b:
            newtag = Tag("definition")
            self.play(ReplacementTransform(tag,newtag), FadeOut(inp), FadeOut(out), FadeOut(ia), FadeOut(oa), run_time=.7)
            tag = newtag
            upper = Node("Active", color=BLUE, width=2.7, height=1.4).move_to(LEFT*3+UP*.7)
            reservoir = Rectangle(width=.7,height=.3,color=BLUE,fill_opacity=.5).move_to(LEFT*3+UP*1.15)
            passive = Circle(radius=.48,color=SOFT).move_to(LEFT*3+DOWN*1.7)
            plabel = T("Passive",size=26).next_to(passive,RIGHT,buff=.6)
            push = Arrow(LEFT*5+DOWN*1.7,LEFT*3.55+DOWN*1.7,color=SOFT,buff=0)
            self.play(Transform(obj,upper), FadeIn(reservoir), Create(passive), FadeIn(plabel), GrowArrow(push), run_time=2)
            self.play(passive.animate.shift(RIGHT*.6),plabel.animate.shift(RIGHT*.6),run_time=1.5)
            mover = Agent(color=BLUE).move_to(LEFT*1+UP*.7)
            goal = Circle(radius=.45,color=AMBER).move_to(RIGHT*3.8+UP*.7)
            purpose = T("Purposeful",size=28,color=BLUE).move_to(RIGHT*1.5+UP*1.8)
            branch = Line(LEFT*1.6+UP*.7,RIGHT*3.3+UP*.7,color=FAINT)
            self.play(Create(branch),FadeIn(mover),Create(goal),FadeIn(purpose),run_time=1.5)
            self.play(mover.animate.shift(RIGHT*1.6),run_time=2)
        # Prepare a complete purpose diagram at the cut, after the prior beat has ended.
        self.remove(obj, reservoir, passive, plabel, push, purpose, branch)
        mover.move_to(LEFT*3.5)
        goal.move_to(RIGHT*3.8)
        with self.beat("s02b03") as b:
            initial = Circle(radius=.24,color=MUTED).move_to(LEFT*3.5)
            behavior = T("Behavior",size=28,color=BLUE).move_to(LEFT*3.5+UP*1.2)
            glabel = T("Goal",size=28,color=AMBER).move_to(RIGHT*3.8+UP*1.2)
            self.add(initial, behavior, glabel)
            self.play(Indicate(mover, color=BLUE), run_time=1)
            connector = always_redraw(lambda: Line(mover.get_center(),goal.get_center(),color=FAINT))
            self.add(connector)
            self.play(mover.animate.move_to(RIGHT*3.2),run_time=5)
            self.play(Indicate(goal,color=AMBER),run_time=1)
            self.remove(connector)
        with self.beat("s02b04") as b:
            newtag=Tag("author_interpretation")
            self.play(ReplacementTransform(tag,newtag),FadeOut(mover),FadeOut(initial),FadeOut(behavior),FadeOut(glabel),run_time=.7)
            tag=newtag
            clock=Circle(radius=1.15,color=SOFT).move_to(LEFT*3)
            hand=Line(LEFT*3,LEFT*3+UP*.85,color=BLUE,stroke_width=6)
            short=Line(LEFT*3,LEFT*3+RIGHT*.5,color=SOFT,stroke_width=5)
            center=Dot(LEFT*3,color=SOFT)
            clocklabel=T("Clock",size=30).move_to(LEFT*3+UP*1.65)
            motionlabel=T("Orderly motion",size=26,color=SOFT).move_to(LEFT*3+DOWN*1.65)
            arc=Arc(radius=1.4,start_angle=PI/6,angle=PI*1.5,color=BLUE).move_to(LEFT*3)
            self.play(Create(clock),Create(hand),Create(short),FadeIn(center),FadeIn(clocklabel),FadeIn(motionlabel),Create(arc),run_time=2)
            self.play(Rotate(hand,angle=-TAU,about_point=LEFT*3),run_time=5)
        with self.beat("s02b05") as b:
            newtag=Tag("background")
            self.play(ReplacementTransform(tag,newtag),run_time=.5)
            tag=newtag
            seeker=Triangle(color=BLUE,fill_color=BLUE,fill_opacity=.8).scale(.3).rotate(-PI/2).move_to(RIGHT*.4+DOWN*.6)
            seeklabel=T("Target-seeking machine",size=27,color=BLUE).move_to(RIGHT*2.2+UP*1.6)
            servo=T("Servomechanism",size=26,color=SOFT).move_to(RIGHT*2.2+DOWN*1.8)
            self.play(FadeIn(seeker),FadeIn(seeklabel),FadeIn(servo),run_time=1)
            path=always_redraw(lambda: Line(seeker.get_center(),goal.get_center(),color=FAINT))
            self.add(path)
            self.play(Rotate(seeker,angle=.18),run_time=.8)
            self.play(seeker.animate.move_to(RIGHT*2.8),Rotate(hand,angle=-TAU,about_point=LEFT*3),run_time=5)
            self.remove(path)
        with self.beat("s02b06") as b:
            newtag=Tag("limitation")
            self.play(ReplacementTransform(tag,newtag),FadeOut(seeklabel),FadeOut(servo),arc.animate.set_stroke(opacity=.25),run_time=.7)
            tag=newtag
            purpose=T("Purpose",size=30,color=SOFT).move_to(RIGHT*2.2+UP*1.6)
            ret=CurvedArrow(goal.get_center()+DOWN*.5,seeker.get_center()+DOWN*.5,angle=-PI/2,color=TEAL)
            error=T("Error signal",size=27,color=TEAL).move_to(RIGHT*3.2+DOWN*1.65)
            self.play(FadeIn(purpose),Create(ret),FadeIn(error),run_time=2)
            signal=Dot(ret.get_start(),color=TEAL,radius=.1)
            self.play(FadeIn(signal),run_time=.3)
            self.play(MoveAlongPath(signal,ret),run_time=3)
            self.play(FadeOut(signal),Indicate(seeker,color=TEAL),run_time=1)
