# storyboard: 5ffdc1c980754595
from aisr_kit import *

class S05(NarratedScene):
    def construct(self):
        with self.beat("s05b01") as b:
            heading = Heading("From correction to safety")
            tag = Tag("future_scenario")
            corridor = VGroup(Line([-5.7,1.3,0],[5.7,1.3,0],color=FAINT),Line([-5.7,-1.3,0],[5.7,-1.3,0],color=FAINT))
            robot = Agent(color=BLUE).move_to([-5,0,0])
            goal = Circle(radius=.44,color=AMBER).move_to([4.8,.7,0])
            destination = T("Destination",size=26,color=AMBER).move_to([4.5,2,0])
            obstacle = Circle(radius=.23,color=SAND).move_to([-.5,0,0])
            future = Circle(radius=.23,color=SAND,stroke_opacity=.5).move_to([-.5,.75,0])
            prediction = T("Prediction",size=26,color=SAND).move_to([-.5,2,0])
            feedback = T("Feedback",size=26,color=TEAL).move_to([-1,-2.3,0])
            return_path = CubicBezier([4.4,.7,0],[3,-2.6,0],[-3,-2.6,0],[-4.7,0,0]).set_stroke(TEAL,2)
            pulse = Dot(radius=.09,color=TEAL)
            self.play(FadeIn(heading),FadeIn(tag),Create(corridor),FadeIn(robot),Create(goal),FadeIn(destination),FadeIn(obstacle),run_time=1.5)
            self.play(Create(return_path),FadeIn(feedback),MoveAlongPath(pulse,return_path),run_time=3)
            self.play(Create(future),FadeIn(prediction),obstacle.animate.move_to([-.5,.75,0]),run_time=2)
            self.remove(pulse)
        with self.beat("s05b02") as b:
            set_label = T("Set destination",size=26,color=AMBER).move_to([4.2,2,0])
            intended = Rectangle(width=.85,height=1,color=SAND).move_to([4.8,-2,0])
            intended_ring = Circle(radius=.6,color=SAND,stroke_opacity=.5).move_to([4.8,-2,0])
            intended_label = T("Intended room",size=26,color=SAND).move_to([2.55,-2.65,0])
            route = CubicBezier([-5,0,0],[-2,-1,0],[1,-.9,0],[4.8,.7,0]).set_stroke(BLUE,3)
            self.play(FadeOut(destination),FadeIn(set_label),FadeOut(return_path),FadeOut(feedback),FadeOut(prediction),FadeOut(future),FadeOut(obstacle),run_time=1.5)
            self.play(Create(route),MoveAlongPath(robot,route),run_time=5)
            self.play(Create(intended),Create(intended_ring),FadeIn(intended_label),run_time=2)
            self.play(Indicate(goal,color=AMBER),Indicate(intended_ring,color=SAND),run_time=2)
            self.wait(b.duration-10.5-1.3)
            self.play(FadeOut(VGroup(tag,corridor,route,set_label,intended,intended_ring,intended_label)),run_time=0.8)
        with self.beat("s05b03") as b:
            next_tag = Tag("limitation")
            machine = Rectangle(width=1.6,height=1,color=BLUE,fill_color=BLUE,fill_opacity=.12).move_to([-3,0,0])
            output = Arrow([-2.1,0,0],[2.7,0,0],color=BLUE,buff=.1)
            loop = VMobject().set_points_as_corners([[3.2,-.5,0],[3.2,-1.5,0],[-3,-1.5,0],[-3,-.6,0]]).set_stroke(TEAL,3)
            loop_tip = Arrow([-3,-1.1,0],[-3,-.5,0],color=TEAL,buff=0)
            essay = T("Conceptual essay",size=40,weight=SEMIBOLD).move_to([0,2,0])
            date = T("January 1943",size=34,color=SOFT).move_to([0,1.15,0])
            source = Source("Rosenblueth et al. (1943)")
            self.play(FadeIn(next_tag),ReplacementTransform(robot,machine),goal.animate.move_to([3.2,0,0]),run_time=2)
            tag = next_tag
            self.play(GrowArrow(output),Create(loop),GrowArrow(loop_tip),FadeIn(essay),FadeIn(date),FadeIn(source),run_time=3)
            self.play(Indicate(essay,color=SOFT),run_time=1.5)
        with self.beat("s05b04") as b:
            next_tag = Tag("background")
            goal_label = T("Goal",size=38,color=AMBER,weight=SEMIBOLD).move_to([3.2,1.0,0])
            correction = T("Correction",size=40,color=INK,weight=SEMIBOLD).move_to([.1,.6,0])
            error = T("Error",size=40,color=INK,weight=SEMIBOLD).move_to([0,-2.1,0])
            doorway = Rectangle(width=.8,height=1.1,color=SAND).move_to([5.4,0,0])
            relation = DashedLine([3.7,0,0],[4.95,0,0],color=SAND)
            person = VGroup(Circle(radius=.15,color=SAND),Line([0,-.18,0],[0,-.65,0],color=SAND),Line([-.23,-.35,0],[.23,-.35,0],color=SAND)).move_to([5.4,-1.5,0])
            pulse = Dot(radius=.09,color=TEAL)
            self.remove(tag)
            self.add(next_tag)
            self.play(FadeOut(essay),FadeOut(date),run_time=0.7)
            self.play(FadeIn(goal_label),FadeIn(correction),FadeIn(error),run_time=1.3)
            self.play(MoveAlongPath(pulse,loop),run_time=3)
            self.remove(pulse)
            self.play(Create(doorway),Create(relation),FadeIn(person),run_time=2)
            self.play(Indicate(doorway,color=SAND),Indicate(relation,color=SAND),run_time=2)
