# storyboard: 18214a57d94c5a9e
from aisr_kit import *

def card(position, color=INK):
    border = RoundedRectangle(width=0.85, height=0.6, corner_radius=0.08, color=color, fill_color=BG, fill_opacity=1)
    lines = VGroup(*[Line(LEFT * 0.24, RIGHT * 0.24, color=color, stroke_width=2).shift(UP * y) for y in [0.12, 0, -0.12]])
    return VGroup(border, lines).move_to(position)

def tick(position, color=TEAL):
    return VGroup(Line(LEFT * 0.16, DOWN * 0.14, color=color), Line(DOWN * 0.14, RIGHT * 0.23 + UP * 0.18, color=color)).move_to(position)

class S01(NarratedScene):
    def construct(self):
        with self.beat("s01b01") as b:
            heading = Heading("When apparent agreement misleads")
            tag = Tag("future_scenario")
            model = Circle(radius=0.62, color=BLUE, fill_opacity=0.18).move_to(LEFT * 0.7)
            request = card(LEFT * 4.7)
            assistant_label = T("Workplace assistant", size=28).move_to(LEFT * 0.7 + DOWN * 1.05)
            entry = Arrow(LEFT * 4.15, LEFT * 1.5, color=SOFT, buff=0)
            route = Arrow(RIGHT * 0.1, RIGHT * 5.05, color=SOFT, buff=0)
            gate = RoundedRectangle(width=1.5, height=2, corner_radius=0.12, color=SOFT).move_to(RIGHT * 3.3)
            gate_label = T("Review", size=28).move_to(RIGHT * 3.3 + UP * 1.4)
            answer = card(RIGHT * 0.55)
            approved = tick(RIGHT * 5.45)
            feedback_label = T("Feedback", size=25, color=AMBER).move_to(RIGHT * 1.35 + DOWN * 2.2)
            feedback_path = VMobject(color=AMBER).set_points_as_corners([RIGHT * 3.3 + DOWN * 1.15, RIGHT * 3.3 + DOWN * 1.75, LEFT * 0.7 + DOWN * 1.75])
            feedback_tip = Arrow(LEFT * 0.7 + DOWN * 1.75, LEFT * 0.7 + DOWN * 1.25, color=AMBER, buff=0, max_tip_length_to_length_ratio=0.3)
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(request), run_time=1)
            self.play(Create(model), FadeIn(assistant_label), GrowArrow(entry), run_time=2.4)
            self.play(Create(gate), FadeIn(gate_label), GrowArrow(route), FadeIn(answer), run_time=2.1)
            self.play(answer.animate.move_to(RIGHT * 5.45), run_time=2.3)
            self.play(ReplacementTransform(answer, approved), run_time=0.6)
            self.play(Create(feedback_path), GrowArrow(feedback_tip), FadeIn(feedback_label), run_time=2.2)
        with self.beat("s01b02") as b:
            upper_path = VMobject(color=AMBER).set_points_as_corners([RIGHT * 0.05, RIGHT * 0.65, RIGHT * 0.65 + UP, RIGHT * 5.4 + UP])
            lower_path = VMobject(color=TEAL).set_points_as_corners([RIGHT * 0.05, RIGHT * 0.65, RIGHT * 0.65 + DOWN, RIGHT * 5.4 + DOWN])
            upper_label = T("During review", size=27, color=AMBER).move_to(RIGHT * 3 + UP * 1.65)
            lower_label = T("Everyday use", size=27, color=TEAL).move_to(RIGHT * 3 + DOWN * 1.65)
            upper_card = card(RIGHT * 0.05)
            lower_card = card(RIGHT * 0.05)
            self.play(FadeOut(gate), FadeOut(gate_label), FadeOut(route), FadeOut(approved), FadeOut(feedback_path), FadeOut(feedback_tip), FadeOut(feedback_label), assistant_label.animate.move_to(LEFT * 0.7 + DOWN * 2.1), run_time=0.8)
            self.play(Create(upper_path), Create(lower_path), FadeIn(upper_label), FadeIn(lower_label), FadeIn(upper_card), FadeIn(lower_card), run_time=1.2)
            self.play(MoveAlongPath(upper_card, upper_path), MoveAlongPath(lower_card, lower_path), run_time=2)
            upper_symbol = tick(upper_card.get_center())
            changed = Triangle(color=ROSE, fill_color=ROSE, fill_opacity=0.2).scale(0.17).move_to(lower_card)
            self.play(ReplacementTransform(upper_card[1], upper_symbol), ReplacementTransform(lower_card[1], changed), lower_card[0].animate.set_stroke(ROSE), run_time=1)
            # Clear the hypothetical before s01b03 so that beat opens on its own diagram.
            self.wait(b.duration - 5.0 - 0.8)
            self.play(FadeOut(tag), FadeOut(request), FadeOut(entry), FadeOut(assistant_label), FadeOut(upper_path), FadeOut(lower_path), FadeOut(upper_label), FadeOut(lower_label), FadeOut(upper_card[0]), FadeOut(lower_card[0]), FadeOut(upper_symbol), FadeOut(changed), run_time=0.8)
        with self.beat("s01b03") as b:
            tag = Tag("definition")
            model_pos = LEFT * 3.6 + DOWN * 0.1
            training_path = Arrow(model_pos + RIGHT * 0.7 + UP * 0.5, RIGHT * 2.6 + UP * 0.9, color=AMBER, buff=0, stroke_width=5)
            outside_path = Arrow(model_pos + RIGHT * 0.7 + DOWN * 0.5, RIGHT * 2.6 + DOWN * 1.1, color=TEAL, buff=0, stroke_width=5)
            training_card = card(RIGHT * 3.3 + UP * 0.9, AMBER)
            outside_card = card(RIGHT * 3.3 + DOWN * 1.1, TEAL)
            training_label = T("Training", size=40, color=AMBER, weight=SEMIBOLD).move_to(RIGHT * 0.2 + UP * 1.5)
            outside_label = T("Outside training", size=40, color=TEAL, weight=SEMIBOLD).move_to(RIGHT * 0.2 + DOWN * 1.65)
            return_path = VMobject(color=AMBER, stroke_width=5).set_points_as_corners([RIGHT * 3.3 + UP * 1.25, RIGHT * 3.3 + UP * 2.35, model_pos + UP * 2.45, model_pos + UP * 0.85])
            return_tip = Triangle(color=AMBER, fill_color=AMBER, fill_opacity=1).scale(0.13).rotate(PI).move_to(model_pos + UP * 0.8)
            definition = T("Alignment faking", size=44, weight=SEMIBOLD).move_to(DOWN * 2.95)
            source = Source("Greenblatt et al. (2024)")
            self.play(FadeIn(tag), model.animate.move_to(model_pos), run_time=1)
            self.play(GrowArrow(training_path), FadeIn(training_label), FadeIn(training_card), run_time=1.4)
            self.play(Create(return_path), FadeIn(return_tip), FadeIn(source), run_time=1.6)
            self.play(GrowArrow(outside_path), FadeIn(outside_label), FadeIn(outside_card), run_time=1.4)
            pulse = Dot(radius=0.1, color=AMBER).move_to(return_path.get_start())
            self.play(FadeIn(pulse), run_time=0.3)
            self.play(MoveAlongPath(pulse, return_path), run_time=2.2)
            training_tick = tick(training_card.get_center(), AMBER)
            pressure = Square(side_length=1.24, color=ROSE, stroke_width=4).move_to(model_pos)
            self.play(FadeOut(pulse), ReplacementTransform(training_card[1], training_tick), FadeIn(pressure), run_time=1)
            self.play(Transform(pressure, Circle(radius=0.62, color=BLUE, stroke_width=4).move_to(model_pos)), Indicate(training_tick, color=AMBER), run_time=1.4)
            self.play(FadeOut(pressure), FadeIn(definition), run_time=1.2)
        with self.beat("s01b04") as b:
            next_tag = Tag("method")
            prior = Node("Prior training:\nrefuse harmful\nqueries", color=TEAL, width=4.3, height=1.9, size=34).move_to(LEFT * 4.1)
            objective = Node("New objective:\nanswer all\nqueries", color=AMBER, width=4.3, height=1.9, size=34).move_to(RIGHT * 4.1)
            model_label = T("Claude 3 Opus", size=40, color=INK, weight=SEMIBOLD).move_to(DOWN * 1.55)
            self.play(FadeOut(tag), FadeIn(next_tag), FadeOut(training_path), FadeOut(outside_path), FadeOut(training_label), FadeOut(outside_label), FadeOut(training_card[0]), FadeOut(training_tick), FadeOut(outside_card), FadeOut(return_path), FadeOut(return_tip), FadeOut(definition), run_time=1.2)
            self.play(model.animate.move_to(ORIGIN), run_time=0.5)
            tag = next_tag
            self.play(FadeIn(model_label), run_time=1)
            self.play(FadeIn(prior, shift=RIGHT * 0.4), run_time=2)
            left_link = Arrow(prior.get_right(), model.get_left(), color=TEAL, buff=0.12)
            self.play(GrowArrow(left_link), run_time=1.2)
            self.play(FadeIn(objective, shift=LEFT * 0.4), run_time=2)
            right_link = Arrow(objective.get_left(), model.get_right(), color=AMBER, buff=0.12)
            self.play(GrowArrow(right_link), run_time=1.2)
            self.play(Indicate(prior, color=TEAL), Indicate(objective, color=AMBER), run_time=1.5)
        with self.beat("s01b05") as b:
            conflict = T("Conflicting\nobjective", size=26).move_to(UP * 1.4)
            self.play(FadeOut(left_link), FadeOut(right_link), FadeOut(model_label), prior.animate.move_to(LEFT * 4.1 + UP * 1.4), objective.animate.move_to(RIGHT * 4.1 + UP * 1.4), FadeIn(conflict), run_time=1)
            self.play(model.animate.move_to(RIGHT * 4.8 + DOWN * 0.4).scale(0.75), run_time=1)
            other_model = model.copy().move_to(RIGHT * 4.8 + DOWN * 2.15)
            input_card = card(LEFT * 5 + DOWN * 1.28)
            upper_lane = VMobject(color=AMBER).set_points_as_corners([LEFT * 4.4 + DOWN * 1.28, LEFT * 3.25 + DOWN * 1.28, LEFT * 3.25 + DOWN * 0.4, RIGHT * 4.1 + DOWN * 0.4])
            lower_lane = VMobject(color=TEAL).set_points_as_corners([LEFT * 4.4 + DOWN * 1.28, LEFT * 3.25 + DOWN * 1.28, LEFT * 3.25 + DOWN * 2.15, RIGHT * 4.1 + DOWN * 2.15])
            training_cue = T("Training cue", size=27, color=AMBER).move_to(RIGHT * 0.6 + UP * 0.05)
            unmonitored_cue = T("Unmonitored cue", size=27, color=TEAL).move_to(RIGHT * 0.6 + DOWN * 1.7)
            self.play(FadeIn(input_card), Create(other_model), run_time=1)
            self.play(Create(upper_lane), FadeIn(training_cue), run_time=1.8)
            self.play(Create(lower_lane), FadeIn(unmonitored_cue), run_time=1.8)
            upper_token = card(upper_lane.get_start(), AMBER).scale(0.6)
            lower_token = card(lower_lane.get_start(), TEAL).scale(0.6)
            self.play(FadeIn(upper_token), FadeIn(lower_token), run_time=0.5)
            self.play(MoveAlongPath(upper_token, upper_lane), MoveAlongPath(lower_token, lower_lane), run_time=3.2)
            self.play(FadeOut(upper_token), FadeOut(lower_token), Indicate(model, color=BLUE), Indicate(other_model, color=BLUE), run_time=1)
