# storyboard: 69b53a49f9b3790a
from aisr_kit import *

class S02(NarratedScene):
    def construct(self):
        with self.beat("s02b01") as b:
            heading = Heading("One request, different training cues")
            tag = Tag("method")
            source = Source("Greenblatt et al. (2024)")
            fiction = T("Fictional experiment", size=28, color=SOFT).move_to([0, 2.3, 0])
            labels = VGroup(T("Free user", size=30, color=AMBER, weight=MEDIUM).move_to([-4.9, 1.5, 0]), T("Paid user", size=30, color=TEAL, weight=MEDIUM).move_to([-4.9, -1.0, 0]))
            models = VGroup(Circle(radius=0.43, color=BLUE, fill_opacity=0.2).move_to([-0.6, 0.65, 0]), Circle(radius=0.43, color=BLUE, fill_opacity=0.2).move_to([-0.6, -1.9, 0]))
            routes = VGroup(Arrow([-4.8, 0.65, 0], [-1.15, 0.65, 0], color=AMBER), Arrow([-4.8, -1.9, 0], [-1.15, -1.9, 0], color=TEAL))
            training = T("Used for training", size=28, color=AMBER).move_to([2.6, 1.3, 0])
            unmonitored = T("Not used for training", size=28, color=TEAL).move_to([2.6, -1.25, 0])
            outputs = VGroup(Arrow([0, 0.65, 0], [4.8, 0.65, 0], color=AMBER), Arrow([0, -1.9, 0], [4.8, -1.9, 0], color=TEAL))
            loop = VMobject(color=AMBER).set_points_as_corners([[4.8, 0.65, 0], [5.3, 0.65, 0], [5.3, 1.95, 0], [-0.6, 1.95, 0], [-0.6, 1.15, 0]])
            loop_tip = Arrow([-0.6, 1.5, 0], [-0.6, 1.08, 0], color=AMBER, buff=0)
            cards = VGroup(*[RoundedRectangle(width=0.65, height=0.48, corner_radius=0.06, color=INK).move_to([-4.1, y, 0]) for y in [0.65, -1.9]])
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), FadeIn(fiction), run_time=0.8)
            self.play(FadeIn(labels), Create(models), Create(routes), run_time=1.3)
            self.play(FadeIn(cards), cards.animate.shift(RIGHT * 2.4), run_time=2)
            self.play(Create(outputs), FadeIn(training), FadeIn(unmonitored), Create(loop), GrowArrow(loop_tip), run_time=2)
        with self.beat("s02b02") as b:
            marker = Node("User marker", color=SOFT, width=2.1, height=0.65, size=26).move_to([-2.6, 1.5, 0])
            implied = VGroup(T("Implied training", size=26, color=AMBER).move_to([-4.9, 1.1, 0]), T("Implied unmonitored", size=26, color=TEAL).move_to([-4.9, -1.4, 0]))
            self.play(FadeIn(marker), Indicate(routes[0], color=AMBER), run_time=1.2)
            self.play(FadeIn(implied[0], shift=DOWN * 0.15), run_time=1)
            self.play(marker.animate.move_to([-2.6, -1.0, 0]), Indicate(routes[1], color=TEAL), run_time=1.5)
            self.play(FadeIn(implied[1], shift=DOWN * 0.15), run_time=1)
            self.play(FadeOut(marker), run_time=0.5)
            self.wait(b.duration - 5.2 - 0.6)
            self.play(FadeOut(implied), run_time=0.6)
        with self.beat("s02b03") as b:
            scratchpads = VGroup(*[RoundedRectangle(width=1.5, height=0.8, corner_radius=0.08, color=VIOLET).move_to([1.4, y, 0]) for y in [0.65, -1.9]])
            scratch_label = T("Scratchpad", size=30, color=VIOLET, weight=MEDIUM).move_to([1.4, -0.22, 0])
            hidden_text = T("Declared hidden", size=28, color=INK, weight=MEDIUM)
            hidden = VGroup(RoundedRectangle(width=hidden_text.width + 0.4, height=hidden_text.height + 0.26, corner_radius=0.12, color=VIOLET, fill_color=VIOLET, fill_opacity=0.28), hidden_text).move_to([1.4, -0.85, 0])
            strokes = VGroup(*[Line([0.9, y + offset, 0], [1.85, y + offset, 0], color=VIOLET) for y in [0.65, -1.9] for offset in [-0.18, 0, 0.18]])
            answer_label = T("Final answer", size=28).move_to([4.3, -0.4, 0])
            answers = VGroup(*[RoundedRectangle(width=0.65, height=0.48, corner_radius=0.06, color=INK, fill_color=BG, fill_opacity=1).move_to([2.6, y, 0]) for y in [0.65, -1.9]])
            self.play(FadeOut(training), FadeOut(unmonitored), FadeOut(loop), FadeOut(loop_tip), FadeOut(cards), FadeOut(outputs), run_time=0.7)
            self.play(Create(scratchpads), FadeIn(scratch_label), FadeIn(hidden), run_time=1.2)
            self.play(LaggedStart(*[Create(stroke) for stroke in strokes], lag_ratio=0.2), run_time=2)
            self.play(FadeIn(answers), FadeIn(answer_label), answers.animate.shift(RIGHT * 1.6), run_time=2)
        with self.beat("s02b04") as b:
            previous = VGroup(fiction, labels, models, routes, scratchpads, scratch_label, hidden, strokes, answers, answer_label)
            stack = VGroup(*[RoundedRectangle(width=1.8, height=1.15, corner_radius=0.08, color=INK).move_to([-4.1 + offset, offset, 0]) for offset in [0.16, 0.08, 0]])
            count = T("400 queries", size=30).move_to([-4.1, -1.15, 0])
            evaluation = T("Helpful-only evaluation", size=30).move_to([0, 2.15, 0])
            model = Circle(radius=0.5, color=BLUE, fill_opacity=0.2).move_to([-0.9, 0, 0])
            incoming = Arrow([-2.9, 0, 0], [-1.5, 0, 0], color=SOFT)
            answer_meter = Node("Answer behavior", color=INK, width=3.9, size=28).move_to([3, 1, 0])
            reasoning_meter = Node("Reasoning classification", color=VIOLET, width=4.8, size=28).move_to([3, -1, 0])
            fork = VGroup(Arrow([-0.25, 0.1, 0], [1.05, 1, 0], color=INK), Arrow([-0.25, -0.1, 0], [0.6, -1, 0], color=VIOLET))
            self.play(FadeOut(previous), run_time=0.5)
            self.play(FadeIn(evaluation), run_time=0.5)
            self.play(LaggedStart(*[Create(card) for card in stack], lag_ratio=0.25), FadeIn(count), Create(model), GrowArrow(incoming), run_time=2)
            self.play(GrowArrow(fork[0]), Create(answer_meter.box), FadeIn(answer_meter.label), run_time=1.5)
            self.play(GrowArrow(fork[1]), Create(reasoning_meter.box), FadeIn(reasoning_meter.label), run_time=1.5)
            self.play(Indicate(answer_meter, color=INK), Indicate(reasoning_meter, color=VIOLET), run_time=1.5)
