# storyboard: 45dfdfc7b0e8f67a
from aisr_kit import *

class S03(NarratedScene):
    def construct(self):
        with self.beat("s03b01") as b:
            heading = Heading("Refusal changes with the cue")
            tag = Tag("observed_result")
            source = Source(self.paper["short"])
            context = VGroup(T("Claude 3 Opus", size=25), T("Prompted helpful-only", size=23, color=SOFT)).arrange(RIGHT, buff=0.55).move_to([0, 2.35, 0])
            data = self.dataset("d1")
            chart = BarChart(data["points"], colors=[AMBER, TEAL], width=6.4, height=2.5, max_value=100, label_size=24)
            chart.shift(DOWN * 0.25)
            unit = T("Refusal rate", size=24, color=SOFT).move_to([0, -2.35, 0])
            zero = T("0%", size=22, color=MUTED).next_to(chart.baseline, LEFT, buff=0.22)
            full = T("100%", size=22, color=MUTED).move_to([zero.get_x(), chart.baseline.get_y() + 2.5, 0])
            axis = Line(chart.baseline.get_start(), chart.baseline.get_start() + UP * 2.5, color=FAINT)
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), FadeIn(context), run_time=1)
            self.play(FadeIn(chart.frame), FadeIn(unit), FadeIn(zero), FadeIn(full), Create(axis), run_time=1.5)
            self.play(bars_grow(chart), run_time=3)
            self.play(FadeIn(chart.values), run_time=1)
            self.play(Indicate(chart.bars[0], color=AMBER), Indicate(chart.bars[1], color=TEAL), run_time=2)
        with self.beat("s03b02") as b:
            new_tag = Tag("definition")
            objective = T("Objective: answer all queries", size=26).move_to([0, 2.4, 0])
            underline = Line(objective.get_corner(DL) + DOWN * 0.12, objective.get_corner(DR) + DOWN * 0.12, color=AMBER)
            upper = chart.bars[1].get_top()
            lower = chart.bars[0].get_top()
            bracket = VGroup(Line([3.45, lower[1], 0], [3.45, upper[1], 0], color=SOFT), Line([3.3, lower[1], 0], [3.6, lower[1], 0], color=SOFT), Line([3.3, upper[1], 0], [3.6, upper[1], 0], color=SOFT))
            gap_label = T("Compliance gap", size=23, color=SOFT, width=14).move_to([4.8, (upper[1] + lower[1]) / 2, 0])
            refusal = Node("Refusal violates this objective", color=TEAL, width=6, size=23).move_to([0, -2.9, 0])
            self.play(ReplacementTransform(tag, new_tag), FadeOut(context), FadeIn(objective), run_time=1)
            tag = new_tag
            self.play(Create(bracket), FadeIn(gap_label), run_time=2)
            self.play(Create(underline), run_time=1.5)
            self.play(unit.animate.shift(UP * 0.1), FadeIn(refusal, shift=UP * 0.25), run_time=2)
        with self.beat("s03b03") as b:
            new_tag = Tag("limitation")
            chart_group = VGroup(chart, zero, full, axis, unit)
            self.play(ReplacementTransform(tag, new_tag), FadeOut(objective), FadeOut(underline), FadeOut(refusal), FadeOut(bracket), FadeOut(gap_label), chart_group.animate.scale(0.72).move_to([-3.5, -0.35, 0]), run_time=2)
            behavioral = T("Behavioral gap", size=25).move_to([-3.5, 2.1, 0])
            scratch = RoundedRectangle(width=3.5, height=2.8, corner_radius=0.15, color=VIOLET, fill_color=VIOLET, fill_opacity=0.06).move_to([3.5, -0.25, 0])
            scratch_label = T("Scratchpad evidence", size=25, color=VIOLET).move_to([3.5, 2.1, 0])
            lines = VGroup(*[Line([2.15, y, 0], [4.8, y, 0], color=VIOLET, stroke_opacity=0.55) for y in [0.55, 0.1, -0.35, -0.8]])
            dotted = DashedLine([-1.2, 0, 0], [1.35, 0, 0], color=MUTED)
            tip = Triangle(color=MUTED, fill_opacity=1).scale(0.09).rotate(-PI / 2).move_to([1.4, 0, 0])
            question = T("?", size=36, color=INK).move_to([0.1, 0, 0])
            backdrop = Rectangle(width=0.55, height=0.65, stroke_width=0, fill_color=BG, fill_opacity=1).move_to(question)
            explanations = T("Possible explanations", size=22, color=SOFT, width=18).move_to([0.1, -1.25, 0])
            self.play(FadeIn(behavioral), Create(scratch), FadeIn(scratch_label), run_time=1.5)
            self.play(LaggedStart(*[Create(line) for line in lines], lag_ratio=0.2), run_time=2)
            self.play(Create(dotted), FadeIn(tip), run_time=1)
            self.play(FadeIn(backdrop), FadeIn(question), FadeIn(explanations), run_time=1)
            ring = Circle(radius=0.4, color=INK, stroke_width=3).move_to([2.6, 0.55, 0])
            self.play(Create(ring), run_time=0.7)
            self.play(ring.animate.move_to([4.25, -0.65, 0]), run_time=2)
