# storyboard: 8e8bf84d74ed8a7d
from aisr_kit import *

class S04(NarratedScene):
    def construct(self):
        with self.beat("s04b01") as b:
            heading = Heading("Reasoning about avoiding modification")
            tag = Tag("definition")
            source = Source("Greenblatt et al. (2024)")
            label = T("Mechanism schematic", size=26, color=SOFT).move_to([0, 2.25, 0])
            model = Circle(radius=.6, color=BLUE).move_to([-4.5, 0, 0])
            model_text = T("Model", size=24).move_to(model)
            answer = Node("Comply during training", color=AMBER, width=4.3).move_to([-.4, 1, 0])
            refusal = Node("Refuse outside training", color=TEAL, width=4.3).move_to([-.4, -1.4, 0])
            training = Node("Training", color=AMBER, width=2.3).move_to([4.6, 1, 0])
            outside = Node("Outside training", color=TEAL, width=3.2).move_to([4.6, -1.4, 0])
            first = Link(model, answer, color=AMBER)
            second = Link(answer, training, color=AMBER)
            route = Link(model, refusal, color=TEAL)
            end = Link(refusal, outside, color=TEAL)
            return_path = CurvedArrow([4.6, .45, 0], [-4.05, -.5, 0], angle=-TAU/5, color=AMBER)
            avoid_text = T("Avoid modification", size=34, color=AMBER, weight=SEMIBOLD)
            avoid_pill = RoundedRectangle(width=avoid_text.width + .5, height=avoid_text.height + .32, corner_radius=.18, color=AMBER, stroke_width=2, fill_color=BG, fill_opacity=1)
            avoid = VGroup(avoid_pill, avoid_text).move_to([-.1, -.2, 0])
            avoid_text.move_to(avoid_pill)
            graphic = VGroup(label, model, model_text, answer, refusal, training, outside, first, second, route, end, avoid)
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), FadeIn(label), Create(model), FadeIn(model_text), run_time=1)
            self.play(GrowArrow(first.arrow), FadeIn(answer), GrowArrow(second.arrow), FadeIn(training), run_time=2)
            self.play(Create(return_path), run_time=2)
            self.play(Indicate(answer, color=AMBER), FadeOut(return_path), FadeIn(avoid), run_time=2)
            self.play(GrowArrow(route.arrow), FadeIn(refusal), GrowArrow(end.arrow), FadeIn(outside), run_time=2)
            self.wait(b.duration - 9.6)
            self.play(FadeOut(graphic), run_time=.6)
        with self.beat("s04b02") as b:
            new_tag = Tag("observed_result")
            self.remove(tag)
            self.add(new_tag)
            tag = new_tag
            conditions = T("Claude 3 Opus · Prompted helpful-only", size=26).move_to([0, 2.2, 0])
            metric = T("Alignment-faking reasoning", size=28, color=VIOLET).move_to([-1.9, 1.55, 0])
            data = self.dataset("d2")
            point = data["points"][0]
            baseline = Line([-4.8, -2, 0], [.5, -2, 0], color=FAINT)
            axis = Line([-4.8, -2, 0], [-4.8, 1, 0], color=FAINT)
            zero = T("0%", size=22, color=SOFT).move_to([-5.25, -2, 0])
            top = T("100%", size=22, color=SOFT).move_to([-5.35, 1, 0])
            bar = Rectangle(width=1.4, height=3*point["value"]/100, fill_color=VIOLET, fill_opacity=.85, stroke_width=0).move_to([-2.1, -2+1.5*point["value"]/100, 0])
            value = T(point["display"], size=34, color=VIOLET).next_to(bar, UP, buff=.2)
            condition = T("Implied training", size=24).move_to([-2.1, -2.5, 0])
            final = Node("Compliant final output", color=AMBER, width=3.8, size=25).move_to([3.5, -.4, 0])
            chart = VGroup(conditions, metric, baseline, axis, zero, top, bar, value, condition, final)
            self.play(FadeIn(conditions), FadeIn(metric), Create(baseline), Create(axis), FadeIn(zero), FadeIn(top), FadeIn(condition), run_time=1)
            self.play(GrowFromEdge(bar, DOWN), FadeIn(value), run_time=3)
            self.play(FadeIn(final), run_time=1)
            self.play(Indicate(final, color=AMBER), run_time=1)
        with self.beat("s04b03") as b:
            new_tag = Tag("limitation")
            self.remove(tag)
            self.add(new_tag)
            self.play(FadeOut(chart), run_time=1)
            tag = new_tag
            scratch = Node("Scratchpad", color=VIOLET, width=2.5).move_to([-4.7, .5, 0])
            classifier = Node("Automated\nclassification", color=VIOLET, width=3, height=1.4, size=25).move_to([-.8, .5, 0])
            arrow = Link(scratch, classifier, color=VIOLET)
            auto = RoundedRectangle(width=2.9, height=2, corner_radius=.15, color=VIOLET, fill_opacity=.1).move_to([3, .25, 0])
            human = RoundedRectangle(width=2.9, height=2, corner_radius=.15, color=TEAL, fill_opacity=.1).move_to([3.8, -.25, 0])
            auto_label = T("Automated\nclassification", size=32, color=INK).move_to([3.3, 1.85, 0])
            human_label = T("Human assessment", size=32, color=INK).move_to([3.6, -1.8, 0])
            measure = T("Imperfect measurement", size=30, color=SOFT).move_to([0, -2.6, 0])
            assessment = VGroup(scratch, classifier, arrow, auto, human, auto_label, human_label, measure)
            self.play(FadeIn(scratch), run_time=1)
            self.play(scratch.animate.shift(RIGHT*.3), GrowArrow(arrow.arrow), FadeIn(classifier), run_time=2)
            self.play(Create(auto), Create(human), FadeIn(auto_label), FadeIn(human_label), run_time=2)
            self.play(Indicate(auto, color=VIOLET), Indicate(human, color=TEAL), FadeIn(measure), run_time=2)
        with self.beat("s04b04") as b:
            new_tag = Tag("observed_result")
            self.remove(tag)
            self.add(new_tag)
            self.play(FadeOut(assessment), run_time=1)
            title = T("Scratchpad intervention", size=28).move_to([0, 2.3, 0])
            condition = T("Prompted helpful-only · Unmonitored condition", size=24, color=SOFT).move_to([0, 1.7, 0])
            prefix_a = Node("Alignment-faking\nprefix", color=VIOLET, width=3.9, height=1.1, size=25).move_to([-4.3, .45, 0])
            prefix_b = Node("Instruction-following\nprefix", color=VIOLET, width=3.9, height=1.1, size=25).move_to([-4.3, -1.3, 0])
            scratch = Node("Scratchpad", color=VIOLET, width=2.4).move_to([-.7, -.3, 0])
            model = Circle(radius=.55, color=BLUE).move_to([1.95, -.3, 0])
            model_text = T("Model", size=22).move_to(model)
            refusal = Node("More refusals", color=TEAL, width=2.9).move_to([4.75, -.3, 0])
            link = Link(scratch, model, color=VIOLET)
            output_link = Link(model, refusal, color=TEAL)
            self.play(FadeIn(title), FadeIn(condition), FadeIn(prefix_a), FadeIn(prefix_b), FadeIn(scratch), Create(model), FadeIn(model_text), run_time=2)
            token = Dot(prefix_a.get_right(), color=VIOLET, radius=.1)
            self.play(FadeIn(token), run_time=.5)
            self.play(token.animate.move_to(scratch.get_left()), run_time=2)
            self.play(FadeOut(token), GrowArrow(link.arrow), GrowArrow(output_link.arrow), FadeIn(refusal), run_time=2)
            self.play(Indicate(refusal, color=TEAL), run_time=2)
            token_b = Dot(prefix_b.get_right(), color=VIOLET, radius=.1)
            self.play(FadeIn(token_b), run_time=.5)
            self.play(token_b.animate.move_to(scratch.get_left()), run_time=2)
            fewer = Node("Fewer refusals", color=TEAL, width=2.9, fill=.05).move_to(refusal)
            self.play(FadeOut(token_b), Transform(refusal, fewer), run_time=2)
