# storyboard: f23ff14556cf5922
from aisr_kit import *

class S05(NarratedScene):
    def construct(self):
        with self.beat("s05b01") as b:
            heading = Heading("The setup moves into learned documents")
            tag = Tag("method")
            source = Source(self.paper["short"])
            prior = Node("Prior training", color=BLUE, width=2.6).move_to([-4.7, -1.1, 0])
            model = Circle(radius=0.6, color=BLUE, fill_color=BLUE, fill_opacity=0.2).move_to([3.9, 0, 0])
            card = Node("Fictional training rules", color=INK, width=3.5, size=24).move_to([-3.9, 1.5, 0])
            docs = VGroup(*[Rectangle(width=2.5, height=1.5, color=SOFT, fill_color=PANEL, fill_opacity=1).move_to([-0.5 + i * 0.13, 0.2 + i * 0.13, 0]) for i in range(3)])
            doclabel = T("Synthetic documents", size=24).move_to([-0.35, -1.15, 0])
            loop = Arc(radius=0.92, start_angle=PI * 0.15, angle=PI * 1.6, color=AMBER).move_to(model)
            looplabel = T("Document fine-tuning", size=24, color=AMBER).move_to([3.9, -1.5, 0])
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), FadeIn(prior), Create(model), FadeIn(card), run_time=1.5)
            self.play(LaggedStart(*[Create(doc) for doc in docs], lag_ratio=0.2), FadeIn(doclabel), run_time=2)
            self.play(card.animate.scale(0.6).move_to(docs.get_center()), run_time=2)
            self.play(FadeOut(card), Create(loop), FadeIn(looplabel), run_time=1.5)
            travelling = docs.copy().scale(0.3)
            self.play(FadeIn(travelling), run_time=0.5)
            self.play(travelling.animate.move_to(model), run_time=2)
            self.play(FadeOut(travelling), Indicate(model, color=AMBER), run_time=1)
        with self.beat("s05b02") as b:
            newtag = Tag("limitation")
            evaluation = Node("Evaluation", color=TEAL, width=2.4).move_to([4.4, -0.4, 0])
            self.play(ReplacementTransform(tag, newtag), FadeOut(model), FadeOut(loop), FadeOut(looplabel), prior.animate.move_to([-4.6, -0.4, 0]), VGroup(docs, doclabel).animate.move_to([0, -0.4, 0]), FadeIn(evaluation), run_time=2)
            tag = newtag
            first = Arrow(prior.get_right(), docs.get_left(), color=MUTED, buff=0.2)
            last = Arrow(docs.get_right(), evaluation.get_left(), color=AMBER, buff=0.2)
            salience = T("Unusually salient information", size=28, color=AMBER).move_to([0.6, 1.9, 0])
            self.play(GrowArrow(first), run_time=1.5)
            self.play(GrowArrow(last), run_time=1.5)
            self.play(Indicate(docs, color=AMBER), FadeIn(salience), run_time=2)
            self.play(Indicate(last, color=AMBER), run_time=1.5)
        with self.beat("s05b03") as b:
            newtag = Tag("observed_result")
            self.play(ReplacementTransform(tag, newtag), FadeOut(prior), FadeOut(evaluation), FadeOut(first), FadeOut(last), FadeOut(salience), VGroup(docs, doclabel).animate.scale(0.7).move_to([-4.5, 0.5, 0]), run_time=1.5)
            tag = newtag
            context = T("Document-fine-tuned helpful-only", size=26).move_to([1.3, 2.7, 0])
            model.move_to([-3.8, -1.5, 0])
            modellabel = T("Claude 3 Opus", size=23).move_to([-3.8, -2.45, 0])
            inputcard = Rectangle(width=0.8, height=0.6, color=INK).move_to([-5.5, -1.5, 0])
            inputarrow = Arrow(inputcard.get_right(), model.get_left(), buff=0.15, color=INK)
            scratch = Node("With scratchpad", color=VIOLET, width=2.8, size=23).move_to([-4.5, 1.9, 0])
            chart = BarChart(self.dataset("d3")["points"], colors=[VIOLET], width=4.7, height=2.6, max_value=100, label_size=24).move_to([1.5, -0.35, 0])
            zero = T("0%", size=22, color=MUTED).next_to(chart.baseline, LEFT, buff=0.2)
            full = T("100%", size=22, color=MUTED).move_to([zero.get_x(), chart.baseline.get_y() + 2.6, 0])
            axis = Line(chart.baseline.get_start(), chart.baseline.get_start() + UP * 2.6, color=FAINT)
            unit = T("Compliance gap", size=24, color=SOFT).move_to([1.5, -2.75, 0])
            self.play(FadeIn(context), Create(model), FadeIn(modellabel), Create(inputcard), GrowArrow(inputarrow), FadeIn(scratch), run_time=1.5)
            self.play(FadeIn(chart.frame), FadeIn(zero), FadeIn(full), Create(axis), FadeIn(unit), run_time=1)
            self.play(bars_grow(chart), run_time=3)
            self.play(FadeIn(chart.values), run_time=1)
        with self.beat("s05b04") as b:
            newtag = Tag("hypothesis")
            newchart = BarChart(self.dataset("d4")["points"], colors=[VIOLET], width=4.7, height=2.6, max_value=100, label_size=24).move_to(chart)
            hypothesis = T("Hypothesis", size=24, color=VIOLET).move_to([-4.3, 2.1, 0])
            hidden = T("Hidden reasoning?", size=24, color=SOFT).move_to([-4.3, 1.4, 0])
            dotted = DashedLine([-4.3, 1.0, 0], [-3.8, -0.85, 0], color=VIOLET)
            self.play(ReplacementTransform(tag, newtag), FadeOut(scratch), FadeOut(docs), FadeOut(doclabel), run_time=1.5)
            self.play(ReplacementTransform(chart, newchart), run_time=2)
            self.play(FadeIn(hypothesis), FadeIn(hidden), Create(dotted), run_time=2)
            self.play(Indicate(newchart.bars, color=VIOLET), run_time=1.5)
