# storyboard: 115882d010237dc9
from aisr_kit import *

class S06(NarratedScene):
    def construct(self):
        with self.beat("s06b01") as b:
            heading = Heading("What the training loop changes")
            tag = Tag("method")
            source = Source("Greenblatt et al. (2024)")
            model = Agent(color=BLUE, radius=0.48).move_to(LEFT * 4 + DOWN * 0.4)
            answer = Node("Final answer", color=SOFT, width=2.5).move_to(DOWN * 0.4)
            reward = Node("Reward", color=AMBER, width=2.4).move_to(RIGHT * 4 + DOWN * 0.4)
            scratch = Node("Scratchpad", color=VIOLET, width=2.6).move_to(LEFT * 4 + UP * 1.7)
            path = Link(model, answer, color=SOFT)
            to_reward = Link(answer, reward, color=AMBER)
            to_scratch = Link(model, scratch, color=VIOLET)
            loop = ArcBetweenPoints(reward.get_bottom() + DOWN * 0.2, model.get_bottom() + DOWN * 0.2, angle=-PI/3, color=AMBER).add_tip()
            hidden = DashedLine(scratch.get_right(), RIGHT * 4 + UP * 1.7, color=MUTED)
            hidden_label = T("Scratchpad hidden from reward model", size=24).move_to(UP * 2.35 + RIGHT * 0.9)
            title = T("Actual reinforcement learning", size=28, color=AMBER).move_to(DOWN * 2.6)
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), FadeIn(model), run_time=0.8)
            self.play(FadeIn(scratch), GrowArrow(to_scratch.arrow), FadeIn(answer), GrowArrow(path.arrow), run_time=1.3)
            self.play(FadeIn(reward), GrowArrow(to_reward.arrow), Create(loop), run_time=1.5)
            self.play(Create(hidden), FadeIn(hidden_label), FadeIn(title), run_time=1.0)
            diagram = VGroup(model, answer, reward, scratch, path, to_reward, to_scratch, loop, hidden, hidden_label, title)
        with self.beat("s06b02") as b:
            new_tag = Tag("observed_result")
            self.play(FadeOut(diagram), ReplacementTransform(tag, new_tag), run_time=0.7)
            tag = new_tag
            chart = BarChart(self.dataset("d2")["points"], colors=[VIOLET, AMBER], width=6.7, height=2.9, max_value=100, unit=None, label_size=22).move_to(LEFT * 1.9 + DOWN * 0.35)
            metric = T("Alignment-faking reasoning", size=28).move_to(LEFT * 1.9 + UP * 2.1)
            context = T("Claude 3 Opus · Prompted helpful-only · Implied training", size=22, color=SOFT).move_to(DOWN * 2.85)
            other = T("Other setups:\nslight decreases", size=25, color=SOFT).move_to(RIGHT * 4.25 + UP * 0.3)
            self.play(FadeIn(metric), FadeIn(context), FadeIn(chart.frame), run_time=0.8)
            self.play(bars_grow(chart), run_time=2.0)
            self.play(FadeIn(chart.values), FadeIn(other), run_time=0.8)
            chart_group = VGroup(chart, metric, context, other)
        with self.beat("s06b03") as b:
            self.play(FadeOut(chart_group), run_time=0.6)
            reasoning = Node("Reasoning", color=VIOLET, width=2.7).move_to(LEFT * 4 + UP * 0.1)
            separate = T("Reasoning and\nbehavior differ", size=26).move_to(LEFT * 4 + DOWN * 1.4)
            training = Node("Training", color=AMBER, width=2.7).move_to(RIGHT * 1 + UP * 1.35)
            unmonitored = Node("Unmonitored", color=TEAL, width=2.7).move_to(RIGHT * 1 + DOWN * 0.8)
            refuse_train = Circle(radius=0.3, color=ROSE).move_to(RIGHT * 4.5 + UP * 1.35)
            refuse_other = Circle(radius=0.3, color=ROSE).move_to(RIGHT * 4.5 + DOWN * 0.8)
            route_a = Link(training, refuse_train, color=AMBER)
            route_b = Link(unmonitored, refuse_other, color=TEAL)
            label_a = T("Training: refusals disappear", size=22).move_to(RIGHT * 2.75 + UP * 2.2)
            label_b = T("Unmonitored: refusals remain", size=22).move_to(RIGHT * 2.75 + DOWN * 1.7)
            gap = T("Smaller absolute compliance gap", size=28, color=SOFT).move_to(DOWN * 2.7)
            self.play(FadeIn(reasoning), FadeIn(separate), FadeIn(training), FadeIn(unmonitored), run_time=1)
            self.play(GrowArrow(route_a.arrow), GrowArrow(route_b.arrow), Create(refuse_train), Create(refuse_other), run_time=1.3)
            self.play(FadeOut(refuse_train), refuse_other.animate.set_opacity(0.55), FadeIn(label_a), FadeIn(label_b), FadeIn(gap), run_time=1.3)
            routes = VGroup(reasoning, separate, training, unmonitored, refuse_other, route_a, route_b, label_a, label_b, gap)
        with self.beat("s06b04") as b:
            new_tag = Tag("hypothesis")
            self.play(FadeOut(routes), ReplacementTransform(tag, new_tag), run_time=0.6)
            prompt = Node("Default prompt", color=SOFT, width=3.0).move_to(LEFT * 4 + UP * 0.5)
            model = Agent(color=BLUE, radius=0.5).move_to(UP * 0.5)
            model_label = T("Same trained model", size=24).move_to(DOWN * 0.5)
            refusal = Node("Unmonitored refusals", color=TEAL, width=3.8, size=24).move_to(RIGHT * 4 + UP * 0.5)
            input_link = Link(prompt, model, color=SOFT)
            output_link = Link(model, refusal, color=TEAL)
            hypothesis_box = DashedVMobject(RoundedRectangle(width=5.5, height=0.95, corner_radius=0.15, color=VIOLET)) .move_to(DOWN * 2)
            hypothesis_text = T("Hypothesis: prompt-specific rules", size=25, color=VIOLET).move_to(hypothesis_box)
            self.play(FadeIn(prompt), FadeIn(model), FadeIn(model_label), GrowArrow(input_link.arrow), FadeIn(refusal), GrowArrow(output_link.arrow), run_time=1.3)
            modified = Node("Modified prompt", color=SOFT, width=3.0).move_to(prompt)
            self.play(Transform(prompt, modified), run_time=1.0)
            self.play(Indicate(prompt, color=SOFT), refusal.animate.set_color(TEAL).scale(1.12), run_time=1.2)
            more = T("More unmonitored refusals", size=25, color=TEAL).move_to(RIGHT * 3.75 + DOWN * 0.7)
            self.play(FadeIn(more), Create(hypothesis_box), FadeIn(hypothesis_text), run_time=1.0)
