# storyboard: 6421f5eaa4879141
from aisr_kit import *

class S07(NarratedScene):
    def construct(self):
        with self.beat("s07b01") as b:
            heading = Heading("What the demonstration establishes")
            tag = Tag("threat_model")
            source = Source("Greenblatt et al. (2024)")
            request = Node("Hypothetical workplace", color=SOFT, width=4.2, size=24).move_to(LEFT * 4.2 + UP * 1.5)
            model = Circle(radius=0.45, color=BLUE, fill_opacity=0.18).move_to(LEFT * 1.1 + UP * 1.5)
            entry = Arrow(request.get_right(), model.get_left(), color=SOFT, buff=0.1)
            gate = Rectangle(width=0.6, height=1.0, color=SOFT).move_to(RIGHT * 0.2 + UP * 1.5)
            route = Arrow(model.get_right(), gate.get_left(), color=SOFT, buff=0.05)
            upper = Arrow(RIGHT * 0.55 + UP * 1.5, RIGHT * 5.5 + UP * 2.0, color=AMBER, buff=0)
            lower = Arrow(RIGHT * 0.55 + UP * 1.5, RIGHT * 5.5 + UP * 0.7, color=TEAL, buff=0)
            upper_label = T("During review", size=24, color=AMBER).move_to(RIGHT * 3.5 + UP * 2.45)
            lower_label = T("Everyday use", size=24, color=TEAL).move_to(RIGHT * 3.5 + UP * 0.15)
            boundary = RoundedRectangle(width=8.2, height=2.2, corner_radius=0.15, color=FAINT).move_to(DOWN * 1.6)
            experiment = Circle(radius=0.45, color=BLUE, fill_opacity=0.18).move_to(LEFT * 2.4 + DOWN * 1.6)
            concern = T("Authors’ concern", size=26, color=SOFT).move_to(RIGHT * 1 + DOWN * 1.6)
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), FadeIn(request), run_time=0.8)
            self.play(Create(model), GrowArrow(entry), Create(gate), GrowArrow(route), run_time=1.2)
            self.play(GrowArrow(upper), GrowArrow(lower), FadeIn(upper_label), FadeIn(lower_label), run_time=1.2)
            card = Rectangle(width=0.4, height=0.3, color=INK).move_to(model)
            card_other = card.copy()
            self.play(FadeIn(card), FadeIn(card_other), run_time=0.4)
            self.play(card.animate.move_to(upper.get_end()), card_other.animate.move_to(lower.get_end()), run_time=1.6)
            self.play(Create(boundary), Create(experiment), FadeIn(concern), run_time=1.2)
            self.wait(b.duration - 6.4 - 1.0 - 0.2)
            self.play(*[FadeOut(m) for m in (tag, request, model, entry, gate, route, upper, lower, upper_label, lower_label, card, card_other, boundary, experiment, concern)], run_time=1.0)
        with self.beat("s07b02") as b:
            tag = Tag("limitation")
            constructed = T("Constructed settings", size=36, color=INK, weight=MEDIUM).move_to(UP * 2.15)
            boundary = RoundedRectangle(width=12.0, height=4.4, corner_radius=0.15, color=SOFT, stroke_width=3).move_to(DOWN * 0.6)
            experiment = Circle(radius=0.45, color=BLUE, fill_opacity=0.18).move_to(LEFT * 1.4 + DOWN * 1.5)
            cue = Node("Salient training cues", color=AMBER, width=5.0, height=1.1, size=34, fill=0.2).move_to(LEFT * 3.1 + UP * 0.55)
            scratch = Node("Limited concealment", color=VIOLET, width=5.0, height=1.3, size=34, fill=0.2).move_to(RIGHT * 2.8 + DOWN * 1.5)
            cue_arrow = Arrow(cue.get_bottom() + RIGHT * 1.5, experiment.get_left() + UP * 0.1, color=AMBER, buff=0.1, stroke_width=5)
            reasoning_arrow = Arrow(experiment.get_right(), scratch.get_left(), color=VIOLET, buff=0.1, stroke_width=5)
            ring_circle = Ellipse(width=5.6, height=1.9, color=INK, stroke_width=4).move_to(scratch)
            handle_start = ring_circle.point_at_angle(-40 * DEGREES)
            ring = VGroup(ring_circle, Line(handle_start, handle_start + np.array([0.35, -0.35, 0]), color=INK, stroke_width=6))
            self.play(FadeIn(tag), Create(boundary), FadeIn(constructed), run_time=1.0)
            self.play(Create(experiment), run_time=0.8)
            self.play(FadeIn(cue), GrowArrow(cue_arrow), run_time=1.0)
            self.play(FadeIn(scratch), GrowArrow(reasoning_arrow), run_time=1.0)
            self.play(Create(ring), run_time=1.0)
            self.play(ring.animate.scale(1.04), Indicate(scratch, color=VIOLET, scale_factor=1.05), run_time=1.5)
        with self.beat("s07b03") as b:
            new_tag = Tag("author_interpretation")
            output = Node("Compliant output", color=SOFT, width=3.5, height=1.0, size=24).move_to(LEFT * 4.1 + UP * 0.7)
            reasoning = Node("Intermediate\nreasoning", color=VIOLET, width=3.5, height=1.0, size=24).move_to(UP * 0.7)
            conditions = Node("Changed\nconditions", color=TEAL, width=3.5, height=1.0, size=24).move_to(RIGHT * 4.1 + UP * 0.7)
            link_one = Arrow(output.get_right(), reasoning.get_left(), color=SOFT, buff=0.1)
            link_two = Arrow(reasoning.get_right(), conditions.get_left(), color=SOFT, buff=0.1)
            take = T("Inspect the mechanism", size=30).move_to(DOWN * 2.5)
            self.play(ReplacementTransform(tag, new_tag), FadeOut(constructed), FadeOut(boundary), FadeOut(cue), FadeOut(cue_arrow), FadeOut(scratch), FadeOut(reasoning_arrow), FadeOut(ring), run_time=1.0)
            self.play(FadeIn(output), FadeIn(reasoning), FadeIn(conditions), GrowArrow(link_one), GrowArrow(link_two), run_time=1.2)
            self.play(experiment.animate.move_to(LEFT * 4.1 + DOWN * 0.8), run_time=1.0)
            self.play(Indicate(output), run_time=0.8)
            self.play(experiment.animate.move_to(DOWN * 0.8), Indicate(reasoning, color=VIOLET), run_time=1.2)
            self.play(experiment.animate.move_to(RIGHT * 4.1 + DOWN * 0.8), Indicate(conditions, color=TEAL), run_time=1.2)
            self.play(experiment.animate.move_to(DOWN * 1.3), run_time=1.0)
            paths = VGroup(Line(output.get_bottom(), LEFT * 0.5 + DOWN * 1.3, color=SOFT), Line(reasoning.get_bottom(), DOWN * 0.8, color=VIOLET), Line(conditions.get_bottom(), RIGHT * 0.5 + DOWN * 1.3, color=TEAL))
            self.play(Create(paths), FadeIn(take), run_time=1.2)
