# storyboard: 544b1d844b590ddd
from aisr_kit import *

class S02(NarratedScene):
    def construct(self):
        with self.beat('s02b01') as b:
            heading = Heading('Why improve?')
            tag = Tag('author_interpretation')
            source = Source('OMOHUNDRO (2007)')
            current = Circle(radius=0.7, color=TEAL).move_to(LEFT * 4.8)
            improved = RoundedRectangle(width=1.6, height=1.5, color=TEAL).move_to(LEFT * 0.8)
            circuit = VGroup(Line(improved.get_center()+LEFT*0.5, improved.get_center()+RIGHT*0.5, color=TEAL), Circle(radius=0.16,color=TEAL).move_to(improved))
            goal = Node('Same goal', color=AMBER, width=2.2).move_to(RIGHT * 4.8)
            labels = VGroup(T('Current',size=26).next_to(current,DOWN),T('Improved',size=26).next_to(improved,DOWN))
            route = Arrow(current.get_right(),improved.get_left(),color=AMBER,buff=0.15)
            path = Arrow(improved.get_right(),goal.get_left(),color=AMBER,buff=0.15)
            tokens = VGroup(*[Circle(radius=0.12,color=AMBER,fill_opacity=0.8).move_to([x,0.55,0]) for x in [0.8,1.7,2.6]])
            self.play(FadeIn(heading),FadeIn(tag),FadeIn(source),Create(current),FadeIn(labels[0]),run_time=1)
            self.play(GrowArrow(route),ReplacementTransform(current.copy(),improved),Create(circuit),FadeIn(labels[1]),FadeIn(goal),run_time=3)
            self.play(GrowArrow(path),LaggedStart(*[FadeIn(t) for t in tokens],lag_ratio=0.3),run_time=3)
        with self.beat('s02b02') as b:
            self.play(FadeOut(tokens),FadeOut(path),FadeOut(circuit),FadeOut(improved),FadeOut(labels[1]),FadeOut(route),run_time=1)
            upper = Node('Current objective',color=AMBER,width=3.1,size=24).move_to([4.5,1.25,0])
            lower = Node('Changed objective',color=AMBER,width=3.1,fill=0).move_to([4.5,-1.5,0])
            self.play(ReplacementTransform(goal,upper),FadeIn(lower),run_time=1)
            good = Arrow(current.get_right(),upper.get_left(),color=TEAL,buff=0.15)
            bad = Arrow(current.get_right(),lower.get_left(),color=AMBER,buff=0.15)
            spotlight = Circle(radius=0.24,color=INK,fill_opacity=0.2).move_to(current)
            self.play(GrowArrow(good),GrowArrow(bad),FadeIn(spotlight),run_time=2)
            self.play(spotlight.animate.move_to(upper),run_time=3)
            self.play(spotlight.animate.move_to(current),run_time=1)
            self.play(spotlight.animate.move_to(lower.get_left()+LEFT*0.45),run_time=3)
        with self.beat('s02b03') as b:
            self.play(FadeOut(upper),FadeOut(lower),FadeOut(good),FadeOut(bad),FadeOut(spotlight),FadeOut(labels[0]),run_time=1)
            self.play(current.animate.scale(1.5).move_to(LEFT*3.6),run_time=1)
            network = VGroup(*[Line([-4.2+i*0.22,-0.55,0],[-3.1-i*0.16,0.55,0],color=TEAL,stroke_width=2) for i in range(5)])
            thread = VMobject(color=AMBER).set_points_as_corners([[-4.1,-0.3,0],[-3.2,0.4,0],[-4,0.4,0],[-3.2,-0.4,0]])
            implicit = T('Implicit goal',size=26).move_to([-3.6,-1.6,0])
            capsule = Node('Explicit goal',color=AMBER,width=2.4).move_to([0,0,0])
            future = RoundedRectangle(width=3.2,height=2.4,color=TEAL).move_to([3.7,0,0])
            self.play(Create(network),Create(thread),FadeIn(implicit),run_time=3)
            self.play(ReplacementTransform(thread,capsule),run_time=3)
            self.play(Create(future),capsule.animate.move_to(future),run_time=3)
        with self.beat('s02b04') as b:
            newtag = Tag('definition')
            self.play(ReplacementTransform(tag,newtag),FadeOut(network),FadeOut(implicit),FadeOut(current),FadeOut(future),run_time=1)
            tag = newtag
            self.play(capsule.animate.move_to([-4.5,0,0]),run_time=1)
            utility = T('Utility',size=26).move_to([-4.5,-1.3,0])
            outcomes = T('Possible outcomes',size=26).move_to([0,2.2,0])
            dots = VGroup(Circle(radius=0.28,color=AMBER,fill_opacity=0.5).move_to([0,1,0]),Circle(radius=0.16,color=AMBER,fill_opacity=0.5).move_to([0,-1,0]))
            branches = VGroup(*[Arrow(capsule.get_right(),dot.get_left(),color=AMBER,buff=0.15) for dot in dots])
            dial = Circle(radius=0.8,color=AMBER).move_to([4.3,0,0])
            needle = Line(dial.get_center(),dial.get_center()+UP*0.55+RIGHT*0.3,color=AMBER)
            expected = T('Expected utility',size=26).move_to([4.3,-1.5,0])
            gather = VGroup(*[Arrow(dot.get_right(),dial.get_left(),color=AMBER,buff=0.15) for dot in dots])
            self.play(FadeIn(utility),FadeIn(outcomes),LaggedStart(*[GrowArrow(a) for a in branches],lag_ratio=0.3),FadeIn(dots),run_time=3)
            self.play(LaggedStart(*[GrowArrow(a) for a in gather],lag_ratio=0.3),Create(dial),Create(needle),FadeIn(expected),run_time=3)
            self.play(Rotate(needle,angle=-0.5,about_point=dial.get_center()),run_time=2)
        with self.beat('s02b05') as b:
            self.play(FadeOut(tag),FadeIn(Tag('limitation')),FadeOut(utility),FadeOut(outcomes),FadeOut(expected),run_time=1)
            budget = RoundedRectangle(width=8.4,height=3.7,color=SOFT).move_to([1.8,-0.1,0])
            limited = T('Limited computation',size=26).move_to([0,2.2,0])
            wrong = T('Model can be wrong',size=26).move_to([3.5,-2.55,0])
            self.play(Create(budget),FadeIn(limited),run_time=2)
            self.play(budget.animate.stretch_to_fit_width(7.8),run_time=3)
            dotted = DashedLine(dots[1].get_right(),dial.get_left(),color=AMBER)
            self.play(ReplacementTransform(gather[1],dotted),dots[1].animate.shift(DOWN*0.6),FadeIn(wrong),run_time=3)
            self.play(Indicate(dotted,color=ROSE),run_time=2)
        with self.beat('s02b06') as b:
            self.play(*[FadeOut(m) for m in list(self.mobjects) if m not in [heading,source]],run_time=1)
            self.play(FadeIn(Tag('future_scenario')),Create(current.move_to([-4.8,0,0]).scale(0.7)),run_time=1)
            direct = Arrow([-3.9,0.7,0],[3.2,0.7,0],color=AMBER)
            selftext = T('Self-change',size=26).move_to([0,1.25,0])
            gate = VGroup(Line([-0.25,0.25,0],[0.25,1.15,0],color=AMBER,stroke_width=7),Line([-0.25,1.15,0],[0.25,0.25,0],color=AMBER,stroke_width=7))
            assistant = Node('Assistant',color=TEAL,width=2.2).move_to([0,-1.4,0])
            benefit = Node('Same benefit',color=AMBER,width=2.6).move_to([4.8,0,0])
            altleft = Arrow(current.get_bottom(),assistant.get_left(),color=TEAL,buff=0.15)
            altright = Arrow(assistant.get_right(),benefit.get_bottom(),color=TEAL,buff=0.15)
            self.play(GrowArrow(direct),FadeIn(selftext),FadeIn(benefit),run_time=2)
            self.play(Create(gate),run_time=2)
            self.play(GrowArrow(altleft),FadeIn(assistant),GrowArrow(altright),run_time=3)
