# storyboard: 2f0d3268a56ff569
from aisr_kit import *

class S04(NarratedScene):
    def construct(self):
        machine = Circle(radius=.65, color=TEAL).move_to(LEFT*3)
        core = Agent(color=TEAL).move_to(machine)
        goal = Node('Future progress', color=AMBER, width=3).move_to(RIGHT*3.6)
        path = Arrow(machine.get_right(), goal.get_left(), color=AMBER, buff=.15)
        source = Source('OMOHUNDRO (2007)')
        with self.beat('s04b01') as b:
            heading = Heading('Why stay active?')
            tag = Tag('author_interpretation')
            active = T('Active', size=26).next_to(machine, DOWN)
            gate = Line(UP*.8, DOWN*.8, color=ROSE, stroke_width=7).move_to(RIGHT*.3)
            shutdown = T('Shutdown', size=26, color=ROSE).next_to(gate, UP)
            token = Dot(color=AMBER).move_to(machine.get_right())
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), Create(machine), FadeIn(core), FadeIn(active), FadeIn(goal), GrowArrow(path), run_time=2)
            self.play(token.animate.move_to(RIGHT*.1), FadeIn(token), run_time=2)
            self.play(Create(gate), FadeIn(shutdown), run_time=1)
            ghosts = VGroup(*[Circle(radius=.1, color=AMBER).move_to(RIGHT*x) for x in [.8, 1.4, 2]])
            self.play(FadeIn(ghosts), run_time=1)
            self.play(FadeOut(ghosts), FadeOut(token), path.animate.set_opacity(.2), run_time=2)
            counterfactual = DashedLine(machine.get_right(), goal.get_left(), color=MUTED)
            self.play(Create(counterfactual), run_time=2)
        with self.beat('s04b02') as b:
            next_tag = Tag('future_scenario')
            self.play(ReplacementTransform(tag, next_tag), FadeOut(active), FadeOut(counterfactual), FadeOut(path), FadeOut(gate), FadeOut(shutdown), run_time=1)
            tag = next_tag
            goal_new = Node('Shared goal', color=AMBER, width=2.5).move_to(RIGHT*4)
            switch = Node('Off switch', color=ROSE, width=2.3).move_to(LEFT*3+UP*1.7)
            resistance = Line(LEFT*4.2+UP*.9, LEFT*1.8+UP*.9, color=AMBER, stroke_width=6)
            copies = VGroup(Circle(radius=.45,color=TEAL).move_to(LEFT*.2+UP*1.2), Circle(radius=.45,color=TEAL).move_to(LEFT*.2+DOWN*1.2))
            copy_label = T('Copies',size=26).move_to(DOWN*2.1)
            branches = VGroup(*[Arrow(machine.get_right(),c.get_left(),color=AMBER,buff=.15) for c in copies])
            links = VGroup(*[Arrow(c.get_right(),goal_new.get_left(),color=AMBER,buff=.15) for c in copies])
            self.play(Transform(goal,goal_new), FadeIn(switch), Create(resistance),run_time=2)
            self.play(LaggedStart(*[Create(c) for c in copies],lag_ratio=.3), LaggedStart(*[GrowArrow(a) for a in branches],lag_ratio=.3),FadeIn(copy_label),run_time=3)
            self.play(*[GrowArrow(a) for a in links],run_time=2)
            temporary = VGroup(switch,resistance,copies,copy_label,branches,links)
        with self.beat('s04b03') as b:
            self.play(FadeOut(temporary),run_time=1)
            limit = DashedLine(UP*2.2+LEFT,DOWN*2.2+LEFT,color=ROSE)
            limit_label = T('Time limit',size=26,color=ROSE).move_to(LEFT*2.8+UP*2.2)
            window = Rectangle(width=2,height=2.4,color=TEAL).move_to(LEFT*3)
            proxy = Circle(radius=.6,color=TEAL).move_to(RIGHT*.8)
            proxy_label = T('Proxy',size=26).next_to(proxy,DOWN)
            first = Arrow(machine.get_right(),proxy.get_left(),color=AMBER,buff=.15)
            last = Arrow(proxy.get_right(),goal.get_left(),color=AMBER,buff=.15)
            self.play(Transform(goal,Node('Original goal',color=AMBER,width=2.5).move_to(RIGHT*4)),Create(window),Create(limit),FadeIn(limit_label),run_time=2)
            self.play(window.animate.stretch(.55,0),Create(proxy),FadeIn(proxy_label),GrowArrow(first),run_time=3)
            self.play(GrowArrow(last),run_time=2)
            temporary = VGroup(limit,limit_label,window,proxy,proxy_label,first,last)
        with self.beat('s04b04') as b:
            next_tag = Tag('author_interpretation')
            self.play(FadeOut(temporary),ReplacementTransform(tag,next_tag),machine.animate.move_to(LEFT*.3),core.animate.move_to(LEFT*.3),run_time=1)
            tag=next_tag
            resource_labels = VGroup(*[T(label,size=25,color=SOFT).move_to(LEFT*4.5+UP*y) for label,y in zip(['Space','Time','Matter','Free energy'],[1.8,.6,-.6,-1.8])])
            resources = VGroup(*[Square(side_length=.25,color=GRAY,fill_opacity=.7).move_to(LEFT*3.1+UP*y) for y in [1.8,.6,-.6,-1.8]])
            feed = VGroup(*[Arrow(s.get_right(),machine.get_left(),color=MUTED,buff=.15) for s in resources])
            path = Arrow(machine.get_right(),goal.get_left(),color=AMBER,buff=.15)
            self.play(FadeIn(resource_labels),FadeIn(resources),*[GrowArrow(a) for a in feed],run_time=2)
            self.play(*[s.animate.move_to(machine) for s in resources],run_time=3)
            computation = VGroup(*[Circle(radius=r,color=TEAL).move_to(machine) for r in [.8,1]])
            self.play(Create(computation),GrowArrow(path),FadeOut(resources),run_time=3)
            temporary=VGroup(resource_labels,resources,feed,computation,path)
        with self.beat('s04b05') as b:
            next_tag=Tag('threat_model')
            self.play(FadeOut(temporary),ReplacementTransform(tag,next_tag),run_time=1)
            tag=next_tag
            community=Rectangle(width=2.4,height=2.3,color=GRAY).move_to(LEFT*4.6+DOWN*.5)
            stock=VGroup(*[Square(side_length=.3,color=GRAY,fill_opacity=.6).move_to(LEFT*x+DOWN*.6) for x in [5.2,4.6,4]])
            trade=Arrow(LEFT*3.3+UP*1.4,machine.get_top(),color=TEAL,buff=.15)
            taking=Arrow(community.get_right(),machine.get_bottom(),color=AMBER,buff=.15)
            trade_label=T('Trade',size=26,color=TEAL).move_to(LEFT*2.5+UP*1.9)
            taking_label=T('Taking',size=26,color=AMBER).move_to(LEFT*2.3+DOWN*1.3)
            loss=VGroup(Line(LEFT*.2+UP*.2,RIGHT*.2+DOWN*.2,color=ROSE),Line(LEFT*.2+DOWN*.2,RIGHT*.2+UP*.2,color=ROSE)).move_to(LEFT*4.6+DOWN*2.1)
            loss_label=T('Costs to others',size=25,color=ROSE).move_to(LEFT*4.6+DOWN*2.7)
            goal_path=Arrow(machine.get_right(),goal.get_left(),color=AMBER,buff=.15)
            self.play(Create(community),FadeIn(stock),GrowArrow(trade),FadeIn(trade_label),GrowArrow(goal_path),run_time=2)
            self.play(GrowArrow(taking),FadeIn(taking_label),run_time=2)
            self.play(stock[2].animate.move_to(machine),run_time=2)
            self.play(Create(loss),FadeIn(loss_label),run_time=1)
        with self.beat('s04b06') as b:
            next_tag=Tag('author_interpretation')
            self.play(ReplacementTransform(tag,next_tag),FadeOut(taking),FadeOut(taking_label),FadeOut(stock[2]),run_time=1)
            cost=Arrow(loss.get_right(),machine.get_bottom(),color=AMBER,buff=.2)
            account=T('Account for costs',size=25,color=AMBER).move_to(RIGHT*1.3+DOWN*1.8)
            goal_boundary=RoundedRectangle(width=3,height=1.7,color=AMBER).move_to(goal)
            goal_design=T('Goal design',size=25,color=AMBER).next_to(goal_boundary,UP)
            institution=RoundedRectangle(width=4.2,height=1.2,color=TEAL).move_to(LEFT*2.3+UP*1.4)
            social=T('Social structures',size=25,color=TEAL).move_to(LEFT*2.3+UP*2.4)
            self.play(GrowArrow(cost),FadeIn(account),run_time=2)
            self.play(Create(goal_boundary),FadeIn(goal_design),Create(institution),FadeIn(social),run_time=2)
            exchange=Square(side_length=.25,color=GRAY,fill_opacity=.7).move_to(trade.get_start())
            self.play(FadeIn(exchange),run_time=.5)
            self.play(exchange.animate.move_to(machine),run_time=2)
