# storyboard: 88b2a330863d846a
from aisr_kit import *

class S01(NarratedScene):
    def construct(self):
        with self.beat("s01b01") as b:
            heading = Heading("A button is only the beginning")
            tag = Tag("future_scenario")
            example = T("Hypothetical example", size=25, color=SOFT).move_to([0,2.25,0])
            body = RoundedRectangle(width=1.4,height=.7,corner_radius=.12,color=TEAL,fill_opacity=.3)
            wheels = VGroup(*[Circle(radius=.15,color=TEAL,fill_opacity=1).move_to([x,-.48,0]) for x in [-.45,.45]])
            parcel = Square(side_length=.6,color=AMBER,fill_opacity=.25).move_to([0,.65,0])
            cart = VGroup(body,wheels,parcel).move_to([-4,-.4,0])
            door = VGroup(Line([4,-1.6,0],[4,1.4,0]),Line([4,1.4,0],[5.5,1.4,0]),Line([5.5,1.4,0],[5.5,-1.6,0])).set_color(SOFT)
            floor = Line([-6,-1.6,0],[6,-1.6,0],color=FAINT)
            switch = Circle(radius=.35,color=ROSE,fill_opacity=.3).move_to([1.5,1.1,0])
            person = Circle(radius=.26,color=AMBER,fill_opacity=.4).move_to([-1,1.1,0])
            self.play(FadeIn(heading),FadeIn(tag),FadeIn(example),Create(floor),Create(door),run_time=1.5)
            self.play(FadeIn(cart),Create(switch),FadeIn(person),run_time=1)
            self.play(cart.animate.shift(RIGHT*1.3),person.animate.shift(RIGHT*1.7),run_time=3)
        with self.beat("s01b02") as b:
            upper = CubicBezier([-1.9,-.4,0],[-.4,1.6,0],[1.5,1.1,0],[3.5,-.4,0],color=ROSE)
            lower = CubicBezier([-1.9,-.4,0],[-.5,-1.4,0],[2,-1.4,0],[3.5,-.4,0],color=TEAL)
            stoplabel=T("Stop",size=25,color=ROSE).move_to([2.5,1.45,0])
            bypass=T("Bypass",size=25,color=TEAL).move_to([.7,-2,0])
            self.play(Create(upper),FadeIn(stoplabel),run_time=2)
            self.play(Create(lower),FadeIn(bypass),run_time=2)
            self.play(Indicate(lower,color=TEAL),run_time=2)
        with self.beat("s01b03") as b:
            self.play(FadeOut(VGroup(cart,door,floor,switch,person,example,upper,lower,stoplabel,bypass)),FadeOut(tag),run_time=1)
            tag=Tag("threat_model")
            robot=Node("Robot",color=TEAL,width=1.8).move_to([-4,0,0])
            diamond=Square(side_length=1,color=AMBER,fill_opacity=.25).rotate(PI/4).move_to([4,0,0])
            objective=T("Objective",size=28,color=AMBER).move_to([4,-1.2,0])
            arrow=Arrow([-2.9,0,0],[3.1,0,0],color=TEAL)
            halt=Circle(radius=.45,color=ROSE,fill_color=BG,fill_opacity=1).move_to([0,0,0])
            haltlabel=T("Shutdown",size=28,color=ROSE).move_to([0,-1.2,0])
            source=Source("Hadfield-Menell et al. (2016)")
            self.play(FadeIn(tag),FadeIn(robot),Create(diamond),FadeIn(objective),FadeIn(source),run_time=1.5)
            self.play(GrowArrow(arrow),run_time=2)
            self.play(FadeIn(halt),FadeIn(haltlabel),run_time=1)
            self.play(Indicate(halt,color=ROSE),run_time=1.5)
        with self.beat("s01b04") as b:
            self.play(FadeOut(VGroup(arrow,halt,haltlabel,objective)),FadeOut(tag),run_time=1)
            tag=Tag("method")
            paper=T("The Off-Switch Game",size=32).move_to([0,2.25,0])
            human=Circle(radius=.35,color=AMBER,fill_opacity=.3).move_to([0,1,0])
            humanlabel=T("Human",size=25,color=AMBER).move_to([0,1.65,0])
            center=Dot([0,0,0],color=SOFT,radius=.08)
            stem=Arrow([-2.9,0,0],[-.15,0,0],color=TEAL)
            outcomes=VGroup(diamond.copy().scale(.65).move_to([4,1,0]),diamond.copy().scale(.65).set_color(ROSE).move_to([4,-1,0]))
            branches=VGroup(Line([0,0,0],[3.5,1,0],color=AMBER),Line([0,0,0],[3.5,-1,0],color=ROSE))
            self.play(FadeIn(tag),FadeIn(paper),ReplacementTransform(diamond,outcomes),run_time=1.5)
            self.play(GrowArrow(stem),Create(branches),FadeIn(center),run_time=2)
            self.play(Create(human),FadeIn(humanlabel),run_time=1)
        with self.beat("s01b05") as b:
            self.play(FadeOut(VGroup(paper,branches,center,stem,outcomes)),run_time=1)
            uncertain=Square(side_length=1,color=AMBER,fill_opacity=.25).rotate(PI/4).move_to([4,.7,0])
            halo=Circle(radius=1.05,color=AMBER,fill_opacity=.12,stroke_opacity=.3).move_to(uncertain)
            benefit=T("Uncertain benefit",size=25,color=AMBER).move_to([4,2.15,0])
            paths=VGroup(Arrow([-2.9,0,0],[2.9,.7,0],color=TEAL),Arrow([-2.9,0,0],[0,-1.9,0],color=ROSE),Arrow([-2.9,0,0],[-.4,.9,0],color=AMBER))
            labels=VGroup(T("Act",size=25,color=TEAL).move_to([1.5,.85,0]),T("Stop",size=25,color=ROSE).move_to([.65,-2.1,0]),T("Ask",size=25,color=AMBER).move_to([-1.8,1.15,0]))
            self.play(Create(halo),Create(uncertain),FadeIn(benefit),run_time=1.5)
            signal=Dot(human.get_center(),color=AMBER,radius=.1)
            self.play(FadeIn(signal),run_time=.3)
            self.play(signal.animate.move_to(halo.get_center()),run_time=2)
            self.play(FadeOut(signal),LaggedStart(*[GrowArrow(p) for p in paths],lag_ratio=.25),FadeIn(labels),run_time=2)
