# storyboard: 11f6969dadd6f220
from aisr_kit import *

class S02(NarratedScene):
    def construct(self):
        with self.beat("s02b01") as b:
            heading = Heading("What the robot can choose")
            tag = Tag("method")
            source = Source("Hadfield-Menell et al. (2016)")
            robot = RoundedRectangle(width=1.3, height=0.9, corner_radius=0.2, color=TEAL, fill_color=TEAL, fill_opacity=0.2).move_to([-4,0,0])
            robot_label = T("Robot", size=26, color=TEAL).next_to(robot, DOWN)
            human = Circle(radius=0.45, color=AMBER, fill_opacity=0.2).move_to([0,1.7,0])
            human_label = T("Human", size=26, color=AMBER).next_to(human, UP)
            outcome = Square(side_length=0.8, color=AMBER, fill_opacity=0.3).rotate(PI/4).move_to([4,0,0])
            outcome_label = T("Human benefit", size=28, color=AMBER).next_to(outcome, DOWN, buff=0.4)
            halo = Circle(radius=0.95, color=AMBER, fill_opacity=0.08, stroke_opacity=0.35).move_to(outcome)
            robot_arrow = Arrow(robot.get_right(), outcome.get_left(), color=TEAL, buff=0.2)
            human_arrow = Arrow(human.get_right(), outcome.get_top(), color=AMBER, buff=0.2)
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), Create(robot), FadeIn(robot_label), run_time=1.5)
            self.play(Create(human), FadeIn(human_label), Create(outcome), FadeIn(outcome_label), run_time=1.5)
            self.play(GrowArrow(robot_arrow), GrowArrow(human_arrow), run_time=2)
            self.play(FadeIn(halo), run_time=1)
            self.play(halo.animate.scale(1.15), run_time=1.5)
            self.play(halo.animate.scale(1/1.15), run_time=1.5)
        with self.beat("s02b02") as b:
            new_tag = Tag("definition")
            self.play(ReplacementTransform(tag,new_tag), FadeOut(robot_arrow), FadeOut(human_arrow), FadeOut(outcome_label), FadeOut(halo), run_time=1)
            tag = new_tag
            rail_left = Line([-1.6,0,0],[1.2,0,0],color=ROSE,stroke_width=7)
            rail_right = Line([1.2,0,0],[4,0,0],color=AMBER,stroke_width=7)
            rail_labels = VGroup(T("Harmful",size=26,color=ROSE).move_to([-1.6,-0.65,0]),T("Beneficial",size=26,color=AMBER).move_to([4,-0.65,0]))
            utility = T("Utility",size=30).move_to([1.2,-1.5,0])
            belief = Ellipse(width=3.3,height=0.8,color=TEAL,fill_opacity=0.13).move_to([1.2,0,0])
            self.play(outcome.animate.scale(0.35).move_to([4,0,0]), human.animate.move_to([1.2,1.55,0]), human_label.animate.move_to([1.2,2.35,0]), run_time=2)
            self.play(Create(rail_left),Create(rail_right),FadeIn(rail_labels),FadeIn(utility),run_time=2)
            belief_link = Arrow(robot.get_right(),belief.get_left(),color=TEAL,buff=0.2)
            self.play(Create(belief),GrowArrow(belief_link),run_time=2)
            self.play(Indicate(human,color=AMBER),belief.animate.stretch(1.15,0),run_time=2)
        with self.beat("s02b03") as b:
            new_tag=Tag("method")
            self.play(ReplacementTransform(tag,new_tag),FadeOut(rail_left),FadeOut(rail_right),FadeOut(rail_labels),FadeOut(utility),FadeOut(belief),FadeOut(belief_link),run_time=1)
            tag=new_tag
            self.play(human.animate.move_to([0.3,0,0]),human_label.animate.move_to([0.3,0.8,0]),outcome.animate.scale(1/0.35).move_to([4,1.6,0]),run_time=1.5)
            act_path=VMobject(color=TEAL).set_points_as_corners([[-4,0.55,0],[-4,1.6,0],[3.3,1.6,0]])
            act_tip=Arrow([2.8,1.6,0],[3.3,1.6,0],color=TEAL,buff=0)
            act_label=T("Act",size=26,color=TEAL).move_to([-1.6,2.05,0])
            wait_path=Arrow(robot.get_right(),human.get_left(),buff=0.15,color=AMBER)
            wait_label=T("Wait",size=26,color=AMBER).move_to([-1.8,0.45,0])
            stop=Circle(radius=0.45,color=ROSE,fill_opacity=0.2).move_to([4,-0.8,0])
            stop_label=T("Stop",size=26,color=ROSE).next_to(stop,RIGHT,buff=0.3)
            allow_path=Arrow(human.get_right(),outcome.get_left(),buff=0.2,color=AMBER)
            stop_path=Arrow(human.get_right(),stop.get_left(),buff=0.2,color=ROSE)
            self.play(Create(act_path),GrowArrow(act_tip),FadeIn(act_label),run_time=2)
            self.play(GrowArrow(wait_path),FadeIn(wait_label),run_time=1.5)
            self.play(Create(stop),FadeIn(stop_label),GrowArrow(allow_path),run_time=1.5)
            self.play(GrowArrow(stop_path),Indicate(allow_path,color=AMBER),run_time=1.5)
        with self.beat("s02b04") as b:
            new_tag=Tag("definition")
            self.play(ReplacementTransform(tag,new_tag),run_time=0.7)
            tag=new_tag
            self_stop=Circle(radius=0.3,color=ROSE,fill_opacity=0.2).move_to([-0.2,-2,0])
            self_path=VMobject(color=ROSE).set_points_as_corners([[-4.7,0,0],[-5.2,0,0],[-5.2,-2,0],[-0.65,-2,0]])
            self_tip=Arrow([-1.2,-2,0],[-0.65,-2,0],color=ROSE,buff=0)
            self_label=T("Self-stop",size=26,color=ROSE).move_to([-2.1,-2.5,0])
            self.play(Create(self_path),GrowArrow(self_tip),Create(self_stop),FadeIn(self_label),run_time=2)
            self.play(Indicate(act_path,color=TEAL),run_time=1.5)
            self.play(Indicate(wait_path,color=AMBER),Indicate(allow_path,color=AMBER),run_time=1.5)
            self.play(Indicate(self_path,color=ROSE),run_time=1.5)
            human_frame=SurroundingRectangle(human,color=AMBER,buff=0.15,corner_radius=0.1)
            self.play(Create(human_frame),run_time=1.5)
        with self.beat("s02b05") as b:
            new_tag=Tag("theoretical_result")
            self.play(ReplacementTransform(tag,new_tag),FadeOut(human_label),run_time=0.7)
            tag=new_tag
            decision_label=T("Human decision",size=24,color=AMBER).move_to([0.5,0.85,0])
            benefit_rail=Line([1,-2.1,0],[3.8,-2.1,0],color=AMBER,stroke_width=5)
            signal_path=Arrow([2.4,-2.1,0],[0.65,-0.6,0],color=AMBER,buff=0.1)
            signal=Dot(radius=0.1,color=AMBER).move_to([2.4,-2.1,0])
            info=T("Information",size=24,color=AMBER).move_to([3.9,-1.65,0])
            random_line=DashedLine([-0.4,-2.9,0],[2,-2.9,0],color=GRAY)
            random_label=T("Random interruption",size=22,color=GRAY).move_to([3.8,-2.9,0])
            self.play(FadeIn(decision_label),Create(benefit_rail),FadeIn(info),run_time=1.5)
            self.play(GrowArrow(signal_path),FadeIn(signal),run_time=1)
            self.play(MoveAlongPath(signal,signal_path),run_time=2)
            self.play(Create(random_line),FadeIn(random_label),run_time=1.5)
            self.play(FadeOut(random_line),FadeOut(random_label),FadeOut(signal),Indicate(human_frame,color=AMBER),run_time=2)
