# storyboard: 3bc9be300c9fcb4d
from aisr_kit import *

class S03(NarratedScene):
    def construct(self):
        with self.beat('s03b01') as b:
            heading = Heading('Why uncertainty helps')
            tag = Tag('theoretical_result')
            source = Source('Hadfield-Menell et al. (2016)')
            robot = Node('Wait', color=TEAL, width=1.5).move_to(LEFT * 4.8)
            gate = RoundedRectangle(width=1.5, height=3.7, corner_radius=.3, color=AMBER).move_to(LEFT * .6)
            human = Circle(radius=.3, color=AMBER, fill_opacity=.25).move_to(gate.get_center())
            glabel = T('Rational human', size=26, color=AMBER).move_to(UP * 2.35 + LEFT * .6)
            good = Square(side_length=.6, color=AMBER, fill_opacity=.3).rotate(PI / 4).move_to(RIGHT * 4.5 + UP * 1.1)
            bad = Square(side_length=.6, color=ROSE, fill_opacity=.3).rotate(PI / 4).move_to(RIGHT * 4.5 + DOWN * 1.1)
            goodlabel = T('Beneficial', size=26, color=AMBER).next_to(good, RIGHT, buff=.25)
            badlabel = T('Harmful', size=26, color=ROSE).next_to(bad, RIGHT, buff=.25)
            stop = Circle(radius=.3, color=ROSE, fill_opacity=.25).move_to(RIGHT * 1.5 + DOWN * 1.1)
            stopbar = Line(stop.get_center() + LEFT * .17, stop.get_center() + RIGHT * .17, color=ROSE)
            upper = VMobject(color=TEAL).set_points_as_corners([robot.get_right(), [-3,1.1,0], [4,1.1,0]])
            lower = VMobject(color=TEAL).set_points_as_corners([robot.get_right(), [-3,-1.1,0], [1.15,-1.1,0]])
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), FadeIn(robot), run_time=1)
            self.play(Create(gate), FadeIn(human), FadeIn(glabel), run_time=1.5)
            self.play(Create(upper), Create(lower), run_time=2)
            self.play(DrawBorderThenFill(good), DrawBorderThenFill(bad), FadeIn(goodlabel), FadeIn(badlabel), Create(stop), Create(stopbar), run_time=2)
        with self.beat('s03b02') as b:
            proceed = T('Proceed', size=24, color=AMBER).move_to([2.4,1.65,0])
            stoplabel = T('Stop', size=24, color=ROSE).move_to([1.5,-1.8,0])
            token = Dot(robot.get_right(), color=TEAL, radius=.13)
            self.play(FadeIn(token), FadeIn(proceed), run_time=.8)
            self.play(MoveAlongPath(token, upper), run_time=3)
            self.play(Indicate(good), FadeOut(token), run_time=1)
            token2 = Dot(robot.get_right(), color=TEAL, radius=.13)
            self.play(FadeIn(token2), FadeIn(stoplabel), run_time=.8)
            self.play(MoveAlongPath(token2, lower), run_time=3)
            self.play(Indicate(stop), FadeOut(token2), run_time=1)
        with self.beat('s03b03') as b:
            halo = Circle(radius=1.05, color=AMBER, fill_color=AMBER, fill_opacity=.09).move_to([-4.7,0,0])
            uncertainty = T('Uncertain value', size=26, color=AMBER).move_to([-4.7,-2,0])
            newlabel = T('Human decision', size=26, color=AMBER).move_to(glabel)
            possibilities = VGroup(good.copy(), bad.copy()).arrange(RIGHT, buff=.3).move_to([-4.7,0,0])
            self.play(FadeOut(robot), FadeOut(proceed), FadeOut(stoplabel), FadeIn(halo), Transform(glabel,newlabel), run_time=1.5)
            self.play(TransformFromCopy(VGroup(good,bad), possibilities), FadeIn(uncertainty), run_time=2)
            self.play(Indicate(gate, color=AMBER), Indicate(human, color=AMBER), run_time=2)
            self.play(Create(upper.copy().set_color(AMBER)), Indicate(stop), run_time=2)
        with self.beat('s03b04') as b:
            old = VGroup(gate,human,glabel,good,bad,goodlabel,badlabel,stop,stopbar,upper,lower,halo,possibilities,uncertainty)
            self.play(FadeOut(old), run_time=1)
            self.remove(*[m for m in self.mobjects if m not in [heading,tag,source]])
            premise = T('Both remain possible', size=28, color=AMBER).move_to([0,2.2,0])
            choices = VGroup(Node('Act',color=GRAY,width=2),Node('Wait',color=TEAL,width=2),Node('Self-stop',color=GRAY,width=2)).arrange(DOWN,buff=.55).move_to([-4.5,-.1,0])
            risk = Square(side_length=.5,color=ROSE,fill_opacity=.2).rotate(PI/4).move_to([4,1.35,0])
            lost = Square(side_length=.5,color=AMBER,fill_opacity=.2).rotate(PI/4).move_to([4,-1.55,0])
            hg = Circle(radius=.4,color=AMBER,fill_opacity=.2).move_to([0,-.1,0])
            top = Arrow(choices[0].get_right(), risk.get_left(),color=MUTED,buff=.2)
            bottom = VGroup(Line(choices[2].get_right() + RIGHT * .2, [3,-1.55,0],color=MUTED), Line([3,-1.85,0],[3,-1.25,0],color=MUTED))
            middle = Arrow(choices[1].get_right(),hg.get_left(),color=TEAL,buff=.2)
            onward = Arrow(hg.get_right(),[4,-.1,0],color=TEAL,buff=.2)
            self.play(FadeIn(premise), FadeIn(choices), run_time=1.5)
            self.play(GrowArrow(top),Create(risk),Create(bottom),Create(lost),run_time=2)
            self.play(choices[0].animate.set_opacity(.45),choices[2].animate.set_opacity(.45),top.animate.set_opacity(.4),bottom.animate.set_opacity(.4),run_time=1)
            self.play(GrowArrow(middle),Create(hg),GrowArrow(onward),run_time=2)
            self.play(Indicate(choices[1],color=TEAL),Indicate(hg,color=AMBER),run_time=1.5)
        with self.beat('s03b05') as b:
            self.play(FadeOut(VGroup(premise,choices,risk,lost,top,bottom,middle,onward)), Transform(tag,Tag('author_interpretation')),run_time=1.5)
            self.play(hg.animate.move_to([3,0,0]),run_time=1)
            rob = RoundedRectangle(width=1.2,height=.8,corner_radius=.2,color=TEAL,fill_opacity=.25).move_to([-3,0,0])
            uh = Circle(radius=1,color=AMBER,fill_opacity=.08).move_to(rob)
            leftlabel = T('Uncertainty',size=30,color=AMBER).move_to([-3,-1.7,0])
            rightlabel = T('Effective oversight',size=30,color=AMBER).move_to([3,-1.7,0])
            connector = Line([-1.9,0,0],[2.5,0,0],color=AMBER)
            self.play(Create(uh),Create(rob),FadeIn(leftlabel),FadeIn(rightlabel),run_time=2)
            self.play(Create(connector),run_time=1)
            self.play(Indicate(uh),run_time=1.5)
            self.play(Indicate(hg),run_time=1.5)
            self.play(hg.animate.shift(RIGHT*.12),run_time=.4)
            self.play(hg.animate.shift(LEFT*.24),run_time=.5)
            self.play(hg.animate.shift(RIGHT*.12),run_time=.4)
