# storyboard: 7debc5a370f5a270
from aisr_kit import *

class S05(NarratedScene):
    def construct(self):
        with self.beat("s05b01") as b:
            heading = Heading("Back to the stop button")
            tag = Tag("future_scenario")
            source = Source("Hadfield-Menell et al. (2016)")
            caption = T("Hypothetical example", size=26, color=SOFT).move_to(UP * 2.15)
            robot = RoundedRectangle(width=1.4, height=0.9, corner_radius=0.2, color=TEAL, fill_opacity=0.15).move_to(LEFT * 3.6)
            parcel = Square(side_length=0.65, color=AMBER).rotate(PI / 4).move_to(LEFT * 3.6 + UP * 0.8)
            self.play(FadeIn(heading), FadeIn(tag), FadeIn(source), FadeIn(caption), Create(robot), Create(parcel), run_time=1.8)
            cart_body = RoundedRectangle(width=1.7, height=0.7, corner_radius=0.15, color=TEAL, fill_opacity=0.25).move_to(LEFT * 3.6)
            box = Rectangle(width=0.7, height=0.6, color=AMBER, fill_opacity=0.18).move_to(LEFT * 3.6 + UP * 0.66)
            wheels = VGroup(*[Circle(radius=0.16, color=TEAL, fill_opacity=1).move_to(LEFT * x + DOWN * 0.5) for x in [4.1, 3.1]])
            door = VGroup(Line([4, -1.1, 0], [4, 1.45, 0], color=SOFT), Line([4, 1.45, 0], [5.2, 1.45, 0], color=SOFT), Line([5.2, 1.45, 0], [5.2, -1.1, 0], color=SOFT))
            halo = Ellipse(width=5.6, height=1.1, color=AMBER, fill_opacity=0.08, stroke_opacity=0.45).move_to(RIGHT * 0.3)
            path = Arrow(LEFT * 2.5, RIGHT * 3.7, color=TEAL, buff=0)
            human = Circle(radius=0.35, color=AMBER, fill_opacity=0.18).move_to(DOWN * 2 + LEFT * 0.8)
            stop = Circle(radius=0.32, color=ROSE, fill_opacity=0.3).move_to(DOWN * 0.85 + LEFT * 0.8)
            stop_bar = Line(stop.get_center() + LEFT * 0.15, stop.get_center() + RIGHT * 0.15, color=INK, stroke_width=4)
            signal = Arrow(human.get_top(), stop.get_bottom(), color=AMBER, buff=0.08)
            feedback = Arrow(stop.get_top(), [-0.8, -0.12, 0], color=AMBER, buff=0.06)
            label = T("Human feedback", size=25, color=AMBER).next_to(human, RIGHT, buff=0.5)
            self.play(Transform(robot, cart_body), Transform(parcel, box), FadeIn(wheels), Create(door), run_time=1.7)
            self.play(Create(halo), GrowArrow(path), Create(human), Create(stop), Create(stop_bar), run_time=1.8)
            self.play(GrowArrow(signal), GrowArrow(feedback), FadeIn(label), run_time=1.5)
            self.play(Indicate(halo, color=AMBER), run_time=1.1)
            illustration = VGroup(robot, parcel, wheels, door, halo, path, human, stop, stop_bar, signal, feedback, label)
        with self.beat("s05b02") as b:
            next_tag = Tag("limitation")
            self.play(ReplacementTransform(tag, next_tag), FadeOut(caption), illustration.animate.scale(0.55).move_to(LEFT * 3.5 + DOWN * 0.4), run_time=1.7)
            tag = next_tag
            frame = RoundedRectangle(width=6, height=4.5, corner_radius=0.15, color=FAINT).move_to(LEFT * 3.2 + DOWN * 0.3)
            game_label = T("One-shot game", size=27).move_to(LEFT * 3.2 + UP * 1.5)
            branch = VGroup(Line([0.6, 0, 0], [1.4, 0, 0], color=TEAL), Line([1.4, 0, 0], [2.3, 0.75, 0], color=TEAL), Line([1.4, 0, 0], [2.3, -0.75, 0], color=ROSE))
            branch_frame = RoundedRectangle(width=2.25, height=2.3, corner_radius=0.1, color=SOFT).move_to([1.5, 0, 0])
            self.play(Create(frame), FadeIn(game_label), Create(branch_frame), Create(branch), run_time=1.7)
            chain = VGroup(*[VGroup(Line([x, 0, 0], [x + 0.55, 0.5, 0], color=MUTED), Line([x, 0, 0], [x + 0.55, -0.5, 0], color=MUTED)) for x in [3.1, 4.15, 5.2]]).set_opacity(0.4)
            self.play(LaggedStart(*[Create(part) for part in chain], lag_ratio=0.25), run_time=2)
            other_arrow = Arrow([5.8, 0, 0], [3.2, 0, 0], color=GRAY, buff=0).set_opacity(0.6)
            other_label = T("Other information", size=25, color=MUTED).move_to([4.5, 1.1, 0])
            self.play(ReplacementTransform(chain, other_arrow), FadeIn(other_label), run_time=1.8)
            self.play(Indicate(signal, color=AMBER), Indicate(feedback, color=AMBER), run_time=1.4)
        with self.beat("s05b03") as b:
            next_tag = Tag("author_interpretation")
            self.play(ReplacementTransform(tag, next_tag), FadeOut(frame), FadeOut(game_label), FadeOut(branch_frame), FadeOut(branch), FadeOut(other_arrow), FadeOut(other_label), illustration.animate.scale(1 / 0.55).move_to([0.45, -0.45, 0]), run_time=2)
            takeaway = T("Uncertainty makes correction valuable", size=31, color=INK).move_to(UP * 2.15)
            self.play(FadeIn(takeaway), run_time=0.8)
            self.play(Indicate(halo, color=AMBER), Indicate(feedback, color=AMBER), run_time=1.7)
            cart = VGroup(robot, parcel, wheels)
            self.play(cart.animate.shift(RIGHT * 1.15), run_time=2)
            self.play(Indicate(stop, color=ROSE), Indicate(signal, color=AMBER), run_time=1.4)
